/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\invasion_environment.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/invasion_environment.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Scene_1">
          <group name="invasion">
            <group name="Background_Decor">
              <group name="Background_Buildings">
                <mesh name="UFO" geometry={nodes.UFO.geometry} material={materials.city_tex} position={[0, 31, -1]} scale={0.691} />
                <mesh name="Background_Building_1" geometry={nodes.Background_Building_1.geometry} material={materials.city_tex} />
                <mesh name="Background_Building_2" geometry={nodes.Background_Building_2.geometry} material={materials.city_tex} />
                <mesh name="Background_Building_3" geometry={nodes.Background_Building_3.geometry} material={materials.city_tex} />
              </group>
              <mesh name="tree_1" geometry={nodes.tree_1.geometry} material={materials.city_tex} />
              <mesh name="tree_2" geometry={nodes.tree_2.geometry} material={materials.city_tex} />
            </group>
            <group name="Base">
              <group name="Grass_tiles" />
              <group name="gbase_01">
                <mesh name="gbase_01_1" geometry={nodes.gbase_01_1.geometry} material={materials.sidewalk_tile} />
                <mesh name="gbase_01_2" geometry={nodes.gbase_01_2.geometry} material={materials.city_tex} />
                <mesh name="gbase_01_3" geometry={nodes.gbase_01_3.geometry} material={materials.ground_block} />
              </group>
              <group name="gbase_02">
                <mesh name="gbase_02_1" geometry={nodes.gbase_02_1.geometry} material={materials.city_tex} />
                <mesh name="gbase_02_2" geometry={nodes.gbase_02_2.geometry} material={materials.sidewalk_tile} />
              </group>
              <group name="gbase_03">
                <mesh name="gbase_03_1" geometry={nodes.gbase_03_1.geometry} material={materials.city_tex} />
                <mesh name="gbase_03_2" geometry={nodes.gbase_03_2.geometry} material={materials.ground_block} />
                <mesh name="gbase_03_3" geometry={nodes.gbase_03_3.geometry} material={materials.sidewalk_tile} />
              </group>
              <mesh name="ground" geometry={nodes.ground.geometry} material={materials.ground_block} position={[-27.83, 69.149, -25.04]} />
            </group>
            <group name="Buildings">
              <group name="Buildings1">
                <mesh name="Building_01" geometry={nodes.Building_01.geometry} material={materials.city_tex} />
                <mesh name="Building_02" geometry={nodes.Building_02.geometry} material={materials.city_tex} />
                <mesh name="Building_03" geometry={nodes.Building_03.geometry} material={materials.city_tex} />
                <mesh name="Building_04" geometry={nodes.Building_04.geometry} material={materials.city_tex} />
                <mesh name="Building_05" geometry={nodes.Building_05.geometry} material={materials.city_tex} />
                <mesh name="Building_06" geometry={nodes.Building_06.geometry} material={materials.city_tex} />
                <mesh name="Building_07" geometry={nodes.Building_07.geometry} material={materials.city_tex} />
                <group name="Building_08">
                  <mesh name="Building_08_1" geometry={nodes.Building_08_1.geometry} material={materials.city_tex} />
                  <mesh name="Building_08_2" geometry={nodes.Building_08_2.geometry} material={materials.Default_Material} />
                  <mesh name="Building_08_3" geometry={nodes.Building_08_3.geometry} material={materials.lambert2} />
                </group>
                <mesh name="Building_09" geometry={nodes.Building_09.geometry} material={materials.city_tex} />
                <mesh name="Building_10" geometry={nodes.Building_10.geometry} material={materials.city_tex} />
                <mesh name="Building_11" geometry={nodes.Building_11.geometry} material={materials.city_tex} />
                <mesh name="Building_12" geometry={nodes.Building_12.geometry} material={materials.city_tex} />
              </group>
              <group name="Police_Station_Ground">
                <mesh name="Police_Station_Ground_1" geometry={nodes.Police_Station_Ground_1.geometry} material={materials.police_station_tex} />
                <mesh name="Police_Station_Ground_2" geometry={nodes.Police_Station_Ground_2.geometry} material={materials.sidewalk_tile} />
              </group>
              <mesh name="Police_Station_Main" geometry={nodes.Police_Station_Main.geometry} material={materials.police_station_tex} />
            </group>
            <group name="Cars">
              <mesh name="Cars_01_210" geometry={nodes.Cars_01_210.geometry} material={materials.city_tex} position={[0.43, 0, 0]} />
              <mesh name="Cars_02_212" geometry={nodes.Cars_02_212.geometry} material={materials.city_tex} />
              <mesh name="Cars_03_214" geometry={nodes.Cars_03_214.geometry} material={materials.city_tex} />
              <mesh name="Cars_04_216" geometry={nodes.Cars_04_216.geometry} material={materials.city_tex} position={[0.733, 0, 0]} />
            </group>
            <group name="Decor">
              <group name="Billboards">
                <mesh name="Billboards_1" geometry={nodes.Billboards_1.geometry} material={materials['Logo 1']} />
                <mesh name="Billboards_2" geometry={nodes.Billboards_2.geometry} material={materials.city_tex} />
              </group>
              <group name="Decor_01">
                <mesh name="Decor_01_1" geometry={nodes.Decor_01_1.geometry} material={materials.city_tex} />
                <mesh name="Decor_01_2" geometry={nodes.Decor_01_2.geometry} material={materials.Logo} />
              </group>
              <mesh name="Decor_02" geometry={nodes.Decor_02.geometry} material={materials.city_tex} />
              <group name="Decor_03">
                <mesh name="Decor_03_1" geometry={nodes.Decor_03_1.geometry} material={materials.city_tex} />
                <mesh name="Decor_03_2" geometry={nodes.Decor_03_2.geometry} material={materials.police_station_tex} />
              </group>
              <mesh name="Decor_04" geometry={nodes.Decor_04.geometry} material={materials.city_tex} />
              <mesh name="Decor_05" geometry={nodes.Decor_05.geometry} material={materials.city_tex} />
              <mesh name="Decor_06" geometry={nodes.Decor_06.geometry} material={materials.city_tex} />
              <mesh name="Decor_07" geometry={nodes.Decor_07.geometry} material={materials.city_tex} />
              <group name="Decor_08">
                <mesh name="Decor_08_1" geometry={nodes.Decor_08_1.geometry} material={materials.city_tex} />
                <mesh name="Decor_08_2" geometry={nodes.Decor_08_2.geometry} material={materials.police_station_tex} />
              </group>
            </group>
          </group>
          <group name="invasion_phys">
            <group name="Base_StaticMeshComponent0" />
            <group name="Building_01_StaticMeshComponent0" />
            <group name="Building_02_StaticMeshComponent0" />
            <group name="Building_03_StaticMeshComponent0" />
            <group name="Building_04_StaticMeshComponent0" />
            <group name="Building_05_StaticMeshComponent0" />
            <group name="Building_06_StaticMeshComponent0" />
            <group name="Building_07_StaticMeshComponent0" />
            <group name="Building_08_StaticMeshComponent0" />
            <group name="Building_09_StaticMeshComponent0" />
            <group name="Building_10_StaticMeshComponent0" />
            <group name="Building_11_StaticMeshComponent0" />
            <group name="Building_12_StaticMeshComponent0" />
            <group name="Car_11A_1_StaticMeshComponent0" />
            <group name="Car_12A_1_StaticMeshComponent0" />
            <group name="Car_15A__1__StaticMeshComponent0" />
            <group name="Car_15A_StaticMeshComponent0" />
            <group name="Car_4A_StaticMeshComponent0" />
            <group name="Car_4B_StaticMeshComponent0" />
            <group name="Car_6B_StaticMeshComponent0" />
            <group name="Car_7A_StaticMeshComponent0" />
            <group name="Car_8A__4__StaticMeshComponent0" />
            <group name="Car_8A_StaticMeshComponent0" />
            <group name="Decor_01_StaticMeshComponent0" />
            <group name="Decor_02_StaticMeshComponent0" />
            <group name="Decor_03_StaticMeshComponent0" />
            <group name="Police_Station_Main_StaticMeshComponent0" />
            <group name="SM_MERGED_Base_Cube_30_StaticMeshComponent0" />
            <group name="Walls_StaticMeshComponent0" />
          </group>
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/invasion_environment.glb')
