/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\toy_car_racing.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['track-narrow']: THREE.Mesh
    ['track-narrow-cap-back']: THREE.Mesh
    ['track-narrow-cap-front']: THREE.Mesh
    ['track-narrow-corner-large']: THREE.Mesh
    ['track-narrow-corner-large-ramp']: THREE.Mesh
    ['track-narrow-corner-large001']: THREE.Mesh
    ['track-narrow-corner-large002']: THREE.Mesh
    ['track-narrow-corner-small']: THREE.Mesh
    ['track-narrow-corner-small-ramp']: THREE.Mesh
    ['track-narrow-corner-small001']: THREE.Mesh
    ['track-narrow-corner-small002']: THREE.Mesh
    ['track-narrow-corner-small003']: THREE.Mesh
    ['track-narrow-curve']: THREE.Mesh
    ['track-narrow-looping']: THREE.Mesh
    ['track-narrow-straight']: THREE.Mesh
    ['track-narrow-straight-bend']: THREE.Mesh
    ['track-narrow-straight-bend-large']: THREE.Mesh
    ['track-narrow-straight-bump-down']: THREE.Mesh
    ['track-narrow-straight-bump-up']: THREE.Mesh
    ['track-narrow-straight-hill-beginning']: THREE.Mesh
    ['track-narrow-straight-hill-complete']: THREE.Mesh
    ['track-narrow-straight-hill-complete-half']: THREE.Mesh
    ['track-narrow-straight-hill-end']: THREE.Mesh
    ['track-narrow-straight-skew-left']: THREE.Mesh
    ['track-narrow-straight-skew-left-side']: THREE.Mesh
    ['track-narrow-straight-skew-right']: THREE.Mesh
    ['track-narrow-straight-skew-right-side']: THREE.Mesh
    ['track-narrow-straight001']: THREE.Mesh
    ['track-narrow-straight002']: THREE.Mesh
    ['track-narrow-straight003']: THREE.Mesh
    ['track-narrow-straight004']: THREE.Mesh
    ['track-narrow-straight005']: THREE.Mesh
    ['track-narrow-straight006']: THREE.Mesh
    ['track-narrow-straight007']: THREE.Mesh
    ['track-narrow-straight008']: THREE.Mesh
    ['track-narrow-straight009']: THREE.Mesh
    ['track-narrow-straight010']: THREE.Mesh
    ['track-narrow-straight011']: THREE.Mesh
    ['track-narrow-straight012']: THREE.Mesh
    ['track-narrow-straight013']: THREE.Mesh
    ['track-narrow-straight014']: THREE.Mesh
    ['track-narrow-straight015']: THREE.Mesh
    ['track-narrow-straight016']: THREE.Mesh
    ['track-narrow-straight017']: THREE.Mesh
    ['track-road-narrow']: THREE.Mesh
    ['track-road-narrow-cap-back']: THREE.Mesh
    ['track-road-narrow-cap-front']: THREE.Mesh
    ['track-road-narrow-corner-large']: THREE.Mesh
    ['track-road-narrow-corner-large-ramp']: THREE.Mesh
    ['track-road-narrow-corner-small']: THREE.Mesh
    ['track-road-narrow-corner-small-ramp']: THREE.Mesh
    ['track-road-narrow-curve']: THREE.Mesh
    ['track-road-narrow-looping']: THREE.Mesh
    ['track-road-narrow-straight']: THREE.Mesh
    ['track-road-narrow-straight-bend']: THREE.Mesh
    ['track-road-narrow-straight-bend-large']: THREE.Mesh
    ['track-road-narrow-straight-bump-down']: THREE.Mesh
    ['track-road-narrow-straight-bump-up']: THREE.Mesh
    ['track-road-narrow-straight-hill-beginning']: THREE.Mesh
    ['track-road-narrow-straight-hill-complete']: THREE.Mesh
    ['track-road-narrow-straight-hill-complete-half']: THREE.Mesh
    ['track-road-narrow-straight-hill-end']: THREE.Mesh
    ['track-road-narrow-straight-skew-left']: THREE.Mesh
    ['track-road-narrow-straight-skew-left-side']: THREE.Mesh
    ['track-road-narrow-straight-skew-right']: THREE.Mesh
    ['track-road-narrow-straight-skew-right-side']: THREE.Mesh
    ['track-road-wide']: THREE.Mesh
    ['track-road-wide-cap-back']: THREE.Mesh
    ['track-road-wide-cap-front']: THREE.Mesh
    ['track-road-wide-corner-large']: THREE.Mesh
    ['track-road-wide-corner-large-ramp']: THREE.Mesh
    ['track-road-wide-corner-small']: THREE.Mesh
    ['track-road-wide-corner-small-ramp']: THREE.Mesh
    ['track-road-wide-curve']: THREE.Mesh
    ['track-road-wide-straight']: THREE.Mesh
    ['track-road-wide-straight-bend']: THREE.Mesh
    ['track-road-wide-straight-bend-large']: THREE.Mesh
    ['track-road-wide-straight-bump-down']: THREE.Mesh
    ['track-road-wide-straight-bump-up']: THREE.Mesh
    ['track-road-wide-straight-hill-beginning']: THREE.Mesh
    ['track-road-wide-straight-hill-complete']: THREE.Mesh
    ['track-road-wide-straight-hill-complete-half']: THREE.Mesh
    ['track-road-wide-straight-hill-end']: THREE.Mesh
    ['track-road-wide-straight-skew-left']: THREE.Mesh
    ['track-road-wide-straight-skew-left-side']: THREE.Mesh
    ['track-road-wide-straight-skew-right']: THREE.Mesh
    ['track-road-wide-straight-skew-right-side']: THREE.Mesh
    ['track-striped-narrow']: THREE.Mesh
    ['track-striped-narrow-cap-back']: THREE.Mesh
    ['track-striped-narrow-cap-front']: THREE.Mesh
    ['track-striped-narrow-corner-large']: THREE.Mesh
    ['track-striped-narrow-corner-large-ramp']: THREE.Mesh
    ['track-striped-narrow-corner-small_1']: THREE.Mesh
    ['track-striped-narrow-corner-small_2']: THREE.Mesh
    ['track-striped-narrow-corner-small_3']: THREE.Mesh
    ['track-striped-narrow-corner-small_4']: THREE.Mesh
    ['track-striped-narrow-corner-small_5']: THREE.Mesh
    ['track-striped-narrow-corner-small_6']: THREE.Mesh
    ['track-striped-narrow-corner-small_7']: THREE.Mesh
    ['track-striped-narrow-corner-small_8']: THREE.Mesh
    ['track-striped-narrow-corner-small_9']: THREE.Mesh
    ['track-striped-narrow-corner-small_10']: THREE.Mesh
    ['track-striped-narrow-corner-small_11']: THREE.Mesh
    ['track-striped-narrow-corner-small_12']: THREE.Mesh
    ['track-striped-narrow-corner-small_13']: THREE.Mesh
    ['track-striped-narrow-corner-small_14']: THREE.Mesh
    ['track-striped-narrow-corner-small_15']: THREE.Mesh
    ['track-striped-narrow-corner-small-ramp']: THREE.Mesh
    ['track-striped-narrow-corner-small001']: THREE.Mesh
    ['track-striped-narrow-corner-small002']: THREE.Mesh
    ['track-striped-narrow-corner-small003']: THREE.Mesh
    ['track-striped-narrow-curve']: THREE.Mesh
    ['track-striped-narrow-looping']: THREE.Mesh
    ['track-striped-narrow-straight']: THREE.Mesh
    ['track-striped-narrow-straight-bend']: THREE.Mesh
    ['track-striped-narrow-straight-bend-large']: THREE.Mesh
    ['track-striped-narrow-straight-bump-down']: THREE.Mesh
    ['track-striped-narrow-straight-bump-up']: THREE.Mesh
    ['track-striped-narrow-straight-hill-beginning']: THREE.Mesh
    ['track-striped-narrow-straight-hill-complete']: THREE.Mesh
    ['track-striped-narrow-straight-hill-complete-half']: THREE.Mesh
    ['track-striped-narrow-straight-hill-end']: THREE.Mesh
    ['track-striped-narrow-straight-skew-left']: THREE.Mesh
    ['track-striped-narrow-straight-skew-left-side']: THREE.Mesh
    ['track-striped-narrow-straight-skew-right']: THREE.Mesh
    ['track-striped-narrow-straight-skew-right-side']: THREE.Mesh
    ['track-striped-narrow-straight001']: THREE.Mesh
    ['track-striped-narrow-straight002']: THREE.Mesh
    ['track-striped-narrow-straight003']: THREE.Mesh
    ['track-striped-narrow-straight004']: THREE.Mesh
    ['track-striped-narrow-straight005']: THREE.Mesh
    ['track-striped-narrow-straight006']: THREE.Mesh
    ['track-striped-narrow-straight007']: THREE.Mesh
    ['track-striped-narrow-straight008']: THREE.Mesh
    ['track-striped-narrow-straight009']: THREE.Mesh
    ['track-striped-narrow-straight010']: THREE.Mesh
    ['track-striped-narrow-straight011']: THREE.Mesh
    ['track-striped-wide']: THREE.Mesh
    ['track-striped-wide-cap-back']: THREE.Mesh
    ['track-striped-wide-cap-front']: THREE.Mesh
    ['track-striped-wide-corner-large']: THREE.Mesh
    ['track-striped-wide-corner-large-ramp']: THREE.Mesh
    ['track-striped-wide-corner-small']: THREE.Mesh
    ['track-striped-wide-corner-small-ramp']: THREE.Mesh
    ['track-striped-wide-curve']: THREE.Mesh
    ['track-striped-wide-straight']: THREE.Mesh
    ['track-striped-wide-straight-bend']: THREE.Mesh
    ['track-striped-wide-straight-bend-large']: THREE.Mesh
    ['track-striped-wide-straight-bump-down']: THREE.Mesh
    ['track-striped-wide-straight-bump-up']: THREE.Mesh
    ['track-striped-wide-straight-hill-beginning']: THREE.Mesh
    ['track-striped-wide-straight-hill-complete']: THREE.Mesh
    ['track-striped-wide-straight-hill-complete-half']: THREE.Mesh
    ['track-striped-wide-straight-hill-end']: THREE.Mesh
    ['track-striped-wide-straight-skew-left']: THREE.Mesh
    ['track-striped-wide-straight-skew-left-side']: THREE.Mesh
    ['track-striped-wide-straight-skew-right']: THREE.Mesh
    ['track-striped-wide-straight-skew-right-side']: THREE.Mesh
    ['track-wide']: THREE.Mesh
    ['track-wide-cap-back']: THREE.Mesh
    ['track-wide-cap-front']: THREE.Mesh
    ['track-wide-corner-large']: THREE.Mesh
    ['track-wide-corner-large-ramp']: THREE.Mesh
    ['track-wide-corner-small']: THREE.Mesh
    ['track-wide-corner-small-ramp']: THREE.Mesh
    ['track-wide-curve']: THREE.Mesh
    ['track-wide-straight']: THREE.Mesh
    ['track-wide-straight-bend']: THREE.Mesh
    ['track-wide-straight-bend-large']: THREE.Mesh
    ['track-wide-straight-bump-down']: THREE.Mesh
    ['track-wide-straight-bump-up']: THREE.Mesh
    ['track-wide-straight-hill-beginning']: THREE.Mesh
    ['track-wide-straight-hill-complete']: THREE.Mesh
    ['track-wide-straight-hill-complete-half']: THREE.Mesh
    ['track-wide-straight-hill-end']: THREE.Mesh
    ['track-wide-straight-skew-left']: THREE.Mesh
    ['track-wide-straight-skew-left-side']: THREE.Mesh
    ['track-wide-straight-skew-right']: THREE.Mesh
    ['track-wide-straight-skew-right-side']: THREE.Mesh
    ['item-cone043']: THREE.Mesh
    ['item-cone044']: THREE.Mesh
    ['item-cone045']: THREE.Mesh
    ['item-cone046']: THREE.Mesh
    ['item-cone047']: THREE.Mesh
    ['item-cone048']: THREE.Mesh
    ['item-cone049']: THREE.Mesh
    ['item-cone050']: THREE.Mesh
    ['item-cone051']: THREE.Mesh
    ['item-cone052']: THREE.Mesh
    ['item-cone053']: THREE.Mesh
    ['item-cone054']: THREE.Mesh
    ['item-cone055']: THREE.Mesh
    ['item-cone056']: THREE.Mesh
    ['item-cone057']: THREE.Mesh
    ['item-cone058']: THREE.Mesh
    ['item-cone059']: THREE.Mesh
    ['item-cone060']: THREE.Mesh
    ['item-cone061']: THREE.Mesh
    ['item-cone062']: THREE.Mesh
    ['item-cone063']: THREE.Mesh
    ['item-cone064']: THREE.Mesh
    ['item-cone065']: THREE.Mesh
    ['item-cone066']: THREE.Mesh
    ['item-cone067']: THREE.Mesh
    ['item-cone068']: THREE.Mesh
    ['item-cone069']: THREE.Mesh
    ['item-cone070']: THREE.Mesh
    ['item-cone071']: THREE.Mesh
    ['item-cone072']: THREE.Mesh
    ['item-cone073']: THREE.Mesh
    ['item-cone074']: THREE.Mesh
    ['item-cone075']: THREE.Mesh
    ['item-cone076']: THREE.Mesh
    ['item-cone077']: THREE.Mesh
    ['item-cone078']: THREE.Mesh
    ['item-cone079']: THREE.Mesh
    ['item-cone080']: THREE.Mesh
    ['item-cone081']: THREE.Mesh
    ['item-cone082']: THREE.Mesh
    ['item-cone083']: THREE.Mesh
    ['item-cone084']: THREE.Mesh
    ['item-cone085']: THREE.Mesh
    ['item-cone086']: THREE.Mesh
    ['item-cone087']: THREE.Mesh
    ['item-cone088']: THREE.Mesh
    ['item-cone089']: THREE.Mesh
    ['item-cone090']: THREE.Mesh
    ['item-cone091']: THREE.Mesh
    ['item-cone092']: THREE.Mesh
    ['item-cone093']: THREE.Mesh
    ['item-cone094']: THREE.Mesh
    ['item-cone095']: THREE.Mesh
    ['item-cone096']: THREE.Mesh
    ['item-cone097']: THREE.Mesh
    ['item-cone098']: THREE.Mesh
    ['item-cone099']: THREE.Mesh
    ['item-cone100']: THREE.Mesh
    ['item-cone101']: THREE.Mesh
    ['item-cone102']: THREE.Mesh
    ['item-cone103']: THREE.Mesh
    ['item-cone']: THREE.Mesh
    Tree_15_trunk001: THREE.Mesh
    Tree_15_foliage001: THREE.Mesh
    Tree_14_trunk001: THREE.Mesh
    Tree_14_foliage001: THREE.Mesh
    Tree_13_trunk001: THREE.Mesh
    Tree_13_foliage001: THREE.Mesh
    Tree_12_trunk001: THREE.Mesh
    Tree_12_foliage001: THREE.Mesh
    Tree_12_trunk002: THREE.Mesh
    Tree_12_foliage002: THREE.Mesh
    Tree_15_trunk002: THREE.Mesh
    Tree_15_foliage002: THREE.Mesh
    Tree_14_trunk002: THREE.Mesh
    Tree_14_foliage002: THREE.Mesh
    Tree_15_trunk003: THREE.Mesh
    Tree_15_trunk004: THREE.Mesh
    Tree_15_trunk005: THREE.Mesh
    Tree_15_foliage003: THREE.Mesh
    Tree_15_foliage004: THREE.Mesh
    Tree_15_foliage005: THREE.Mesh
    Tree_14_trunk003: THREE.Mesh
    Tree_14_trunk004: THREE.Mesh
    Tree_14_trunk005: THREE.Mesh
    Tree_14_foliage003: THREE.Mesh
    Tree_14_foliage004: THREE.Mesh
    Tree_14_foliage005: THREE.Mesh
    Tree_13_trunk002: THREE.Mesh
    Tree_13_trunk003: THREE.Mesh
    Tree_13_foliage002: THREE.Mesh
    Tree_13_foliage003: THREE.Mesh
    Tree_12_trunk003: THREE.Mesh
    Tree_12_trunk004: THREE.Mesh
    Tree_12_trunk005: THREE.Mesh
    Tree_12_foliage003: THREE.Mesh
    Tree_12_foliage004: THREE.Mesh
    Tree_12_foliage005: THREE.Mesh
    Tree_15_trunk006: THREE.Mesh
    Tree_15_trunk007: THREE.Mesh
    Tree_15_foliage006: THREE.Mesh
    Tree_15_foliage007: THREE.Mesh
    Tree_14_trunk006: THREE.Mesh
    Tree_14_trunk007: THREE.Mesh
    Tree_14_foliage006: THREE.Mesh
    Tree_14_foliage007: THREE.Mesh
    Tree_13_trunk004: THREE.Mesh
    Tree_13_trunk005: THREE.Mesh
    Tree_13_foliage004: THREE.Mesh
    Tree_13_foliage005: THREE.Mesh
    Tree_12_trunk006: THREE.Mesh
    Tree_12_trunk007: THREE.Mesh
    Tree_12_trunk008: THREE.Mesh
    Tree_12_foliage006: THREE.Mesh
    Tree_12_foliage007: THREE.Mesh
    Tree_12_foliage008: THREE.Mesh
    Tree_15_trunk008: THREE.Mesh
    Tree_15_trunk009: THREE.Mesh
    Tree_15_foliage008: THREE.Mesh
    Tree_15_foliage009: THREE.Mesh
    Tree_14_trunk008: THREE.Mesh
    Tree_14_trunk009: THREE.Mesh
    Tree_14_foliage008: THREE.Mesh
    Tree_14_foliage009: THREE.Mesh
    Tree_13_trunk006: THREE.Mesh
    Tree_13_trunk007: THREE.Mesh
    Tree_13_foliage006: THREE.Mesh
    Tree_13_foliage007: THREE.Mesh
    Tree_12_trunk009: THREE.Mesh
    Tree_12_trunk010: THREE.Mesh
    Tree_12_trunk011: THREE.Mesh
    Tree_12_foliage009: THREE.Mesh
    Tree_12_foliage010: THREE.Mesh
    Tree_12_foliage011: THREE.Mesh
    ['vehicle-drag-racer']: THREE.Mesh
    ['wheel-bl']: THREE.Mesh
    ['wheel-br']: THREE.Mesh
    ['wheel-fl']: THREE.Mesh
    ['wheel-fr']: THREE.Mesh
    ['vehicle-racer']: THREE.Mesh
    ['wheel-bl002']: THREE.Mesh
    ['wheel-br002']: THREE.Mesh
    ['wheel-fl002']: THREE.Mesh
    ['wheel-fr002']: THREE.Mesh
    ['vehicle-racer-low']: THREE.Mesh
    ['wheel-bl003']: THREE.Mesh
    ['wheel-br003']: THREE.Mesh
    ['wheel-fl003']: THREE.Mesh
    ['wheel-fr003']: THREE.Mesh
    ['vehicle-speedster']: THREE.Mesh
    ['wheel-bl004']: THREE.Mesh
    ['wheel-br004']: THREE.Mesh
    ['wheel-fl004']: THREE.Mesh
    ['wheel-fr004']: THREE.Mesh
    ['vehicle-suv']: THREE.Mesh
    ['wheel-bl005']: THREE.Mesh
    ['wheel-br005']: THREE.Mesh
    ['wheel-fl005']: THREE.Mesh
    ['wheel-fr005']: THREE.Mesh
    ['vehicle-truck']: THREE.Mesh
    ['wheel-bl006']: THREE.Mesh
    ['wheel-br006']: THREE.Mesh
    ['wheel-fl006']: THREE.Mesh
    ['wheel-fr006']: THREE.Mesh
    ['vehicle-vintage-racer']: THREE.Mesh
    ['wheel-bl007']: THREE.Mesh
    ['wheel-br007']: THREE.Mesh
    ['wheel-fl007']: THREE.Mesh
    ['wheel-fr007']: THREE.Mesh
    ['item-banana']: THREE.Mesh
    ['item-box']: THREE.Mesh
    ['item-coin-bronze']: THREE.Mesh
    ['item-coin-gold']: THREE.Mesh
    ['item-coin-silver']: THREE.Mesh
    ['item-cone001']: THREE.Mesh
    ['item-cone002']: THREE.Mesh
    ['item-cone003']: THREE.Mesh
    ['item-cone004']: THREE.Mesh
    ['item-cone005']: THREE.Mesh
    ['item-cone006']: THREE.Mesh
    ['item-cone007']: THREE.Mesh
    ['item-cone008']: THREE.Mesh
    ['item-cone009']: THREE.Mesh
    ['item-cone010']: THREE.Mesh
    ['item-cone011']: THREE.Mesh
    ['item-cone012']: THREE.Mesh
    ['item-cone013']: THREE.Mesh
    ['item-cone014']: THREE.Mesh
    ['item-cone015']: THREE.Mesh
    ['item-cone016']: THREE.Mesh
    ['item-cone017']: THREE.Mesh
    ['item-cone018']: THREE.Mesh
    ['item-cone019']: THREE.Mesh
    ['item-cone020']: THREE.Mesh
    ['item-cone021']: THREE.Mesh
    ['item-cone022']: THREE.Mesh
    ['item-cone023']: THREE.Mesh
    ['item-cone024']: THREE.Mesh
    ['item-cone025']: THREE.Mesh
    ['item-cone026']: THREE.Mesh
    ['item-cone027']: THREE.Mesh
    ['item-cone028']: THREE.Mesh
    ['item-cone029']: THREE.Mesh
    ['item-cone030']: THREE.Mesh
    ['item-cone031']: THREE.Mesh
    ['item-cone032']: THREE.Mesh
    ['item-cone033']: THREE.Mesh
    ['item-cone034']: THREE.Mesh
    ['item-cone035']: THREE.Mesh
    ['item-cone036']: THREE.Mesh
    ['item-cone037']: THREE.Mesh
    ['item-cone038']: THREE.Mesh
    ['item-cone039']: THREE.Mesh
    ['item-cone040']: THREE.Mesh
    ['item-cone041']: THREE.Mesh
    ['item-cone042']: THREE.Mesh
    Building_1: THREE.Mesh
    Building_2: THREE.Mesh
    Building_3: THREE.Mesh
    Building_4: THREE.Mesh
    Ground_Plane001: THREE.Mesh
    tree: THREE.Mesh
    ['tree-pine']: THREE.Mesh
    Tree_12_foliage: THREE.Mesh
    Tree_12_trunk: THREE.Mesh
    Tree_13_foliage: THREE.Mesh
    Tree_13_trunk: THREE.Mesh
    Tree_14_foliage: THREE.Mesh
    Tree_14_trunk: THREE.Mesh
    Tree_15_foliage: THREE.Mesh
    Tree_15_trunk: THREE.Mesh
    body: THREE.Mesh
    Finish_Line: THREE.Mesh
    gate: THREE.Mesh
    ['gate-finish']: THREE.Mesh
    smoke: THREE.Mesh
    supports: THREE.Mesh
    ['supports-clamp']: THREE.Mesh
    ['supports-diagonal']: THREE.Mesh
    ['supports-wide']: THREE.Mesh
    ['supports-wide-clamp']: THREE.Mesh
    ['supports-wide-diagonal']: THREE.Mesh
    supports001: THREE.Mesh
    supports002: THREE.Mesh
    supports003: THREE.Mesh
    supports004: THREE.Mesh
    supports005: THREE.Mesh
    ['wheel-bl001']: THREE.Mesh
    ['wheel-br001']: THREE.Mesh
    ['wheel-fl001']: THREE.Mesh
    ['wheel-fr001']: THREE.Mesh
    ['wheel-large']: THREE.Mesh
    ['wheel-medium']: THREE.Mesh
    ['wheel-small']: THREE.Mesh
  }
  materials: {
    ['colormap.015']: THREE.MeshStandardMaterial
    ['colormap.016']: THREE.MeshStandardMaterial
    ['colormap.017']: THREE.MeshStandardMaterial
    ['colormap.018']: THREE.MeshStandardMaterial
    ['colormap.019']: THREE.MeshStandardMaterial
    ['colormap.020']: THREE.MeshStandardMaterial
    ['colormap.021']: THREE.MeshStandardMaterial
    ['colormap.022']: THREE.MeshStandardMaterial
    ['colormap.023']: THREE.MeshStandardMaterial
    ['colormap.024']: THREE.MeshStandardMaterial
    ['colormap.025']: THREE.MeshStandardMaterial
    ['colormap.026']: THREE.MeshStandardMaterial
    ['colormap.027']: THREE.MeshStandardMaterial
    ['colormap.028']: THREE.MeshStandardMaterial
    ['colormap.029']: THREE.MeshStandardMaterial
    ['colormap.030']: THREE.MeshStandardMaterial
    ['colormap.031']: THREE.MeshStandardMaterial
    ['colormap.032']: THREE.MeshStandardMaterial
    ['colormap.033']: THREE.MeshStandardMaterial
    ['colormap.034']: THREE.MeshStandardMaterial
    ['colormap.035']: THREE.MeshStandardMaterial
    ['colormap.036']: THREE.MeshStandardMaterial
    ['colormap.037']: THREE.MeshStandardMaterial
    ['colormap.038']: THREE.MeshStandardMaterial
    ['colormap.039']: THREE.MeshStandardMaterial
    ['colormap.040']: THREE.MeshStandardMaterial
    ['colormap.041']: THREE.MeshStandardMaterial
    ['colormap.042']: THREE.MeshStandardMaterial
    ['colormap.043']: THREE.MeshStandardMaterial
    ['colormap.044']: THREE.MeshStandardMaterial
    ['colormap.045']: THREE.MeshStandardMaterial
    ['colormap.046']: THREE.MeshStandardMaterial
    ['colormap.047']: THREE.MeshStandardMaterial
    ['colormap.048']: THREE.MeshStandardMaterial
    ['colormap.049']: THREE.MeshStandardMaterial
    ['colormap.050']: THREE.MeshStandardMaterial
    ['colormap.051']: THREE.MeshStandardMaterial
    ['colormap.052']: THREE.MeshStandardMaterial
    ['colormap.053']: THREE.MeshStandardMaterial
    ['colormap.054']: THREE.MeshStandardMaterial
    ['colormap.055']: THREE.MeshStandardMaterial
    ['colormap.056']: THREE.MeshStandardMaterial
    ['colormap.057']: THREE.MeshStandardMaterial
    ['colormap.058']: THREE.MeshStandardMaterial
    ['colormap.059']: THREE.MeshStandardMaterial
    ['colormap.060']: THREE.MeshStandardMaterial
    ['colormap.061']: THREE.MeshStandardMaterial
    ['colormap.062']: THREE.MeshStandardMaterial
    ['colormap.063']: THREE.MeshStandardMaterial
    ['colormap.064']: THREE.MeshStandardMaterial
    ['colormap.065']: THREE.MeshStandardMaterial
    ['colormap.066']: THREE.MeshStandardMaterial
    ['colormap.067']: THREE.MeshStandardMaterial
    ['colormap.068']: THREE.MeshStandardMaterial
    ['colormap.069']: THREE.MeshStandardMaterial
    ['colormap.070']: THREE.MeshStandardMaterial
    ['colormap.071']: THREE.MeshStandardMaterial
    ['colormap.072']: THREE.MeshStandardMaterial
    ['colormap.073']: THREE.MeshStandardMaterial
    ['colormap.074']: THREE.MeshStandardMaterial
    ['colormap.075']: THREE.MeshStandardMaterial
    ['colormap.076']: THREE.MeshStandardMaterial
    ['colormap.077']: THREE.MeshStandardMaterial
    ['colormap.078']: THREE.MeshStandardMaterial
    ['colormap.079']: THREE.MeshStandardMaterial
    ['colormap.080']: THREE.MeshStandardMaterial
    ['colormap.081']: THREE.MeshStandardMaterial
    ['colormap.082']: THREE.MeshStandardMaterial
    ['colormap.083']: THREE.MeshStandardMaterial
    ['colormap.084']: THREE.MeshStandardMaterial
    ['colormap.085']: THREE.MeshStandardMaterial
    ['colormap.089']: THREE.MeshStandardMaterial
    ['colormap.086']: THREE.MeshStandardMaterial
    ['colormap.090']: THREE.MeshStandardMaterial
    ['colormap.091']: THREE.MeshStandardMaterial
    ['colormap.092']: THREE.MeshStandardMaterial
    ['colormap.093']: THREE.MeshStandardMaterial
    ['colormap.094']: THREE.MeshStandardMaterial
    ['colormap.095']: THREE.MeshStandardMaterial
    ['colormap.096']: THREE.MeshStandardMaterial
    ['colormap.097']: THREE.MeshStandardMaterial
    ['colormap.098']: THREE.MeshStandardMaterial
    ['colormap.099']: THREE.MeshStandardMaterial
    ['colormap.100']: THREE.MeshStandardMaterial
    ['colormap.101']: THREE.MeshStandardMaterial
    ['colormap.087']: THREE.MeshStandardMaterial
    ['colormap.088']: THREE.MeshStandardMaterial
    ['colormap.102']: THREE.MeshStandardMaterial
    ['colormap.103']: THREE.MeshStandardMaterial
    ['colormap.104']: THREE.MeshStandardMaterial
    ['colormap.105']: THREE.MeshStandardMaterial
    ['colormap.106']: THREE.MeshStandardMaterial
    ['colormap.107']: THREE.MeshStandardMaterial
    ['colormap.108']: THREE.MeshStandardMaterial
    ['colormap.109']: THREE.MeshStandardMaterial
    ['colormap.110']: THREE.MeshStandardMaterial
    ['colormap.111']: THREE.MeshStandardMaterial
    ['colormap.112']: THREE.MeshStandardMaterial
    ['colormap.113']: THREE.MeshStandardMaterial
    ['colormap.114']: THREE.MeshStandardMaterial
    ['colormap.115']: THREE.MeshStandardMaterial
    ['colormap.116']: THREE.MeshStandardMaterial
    ['colormap.117']: THREE.MeshStandardMaterial
    ['colormap.118']: THREE.MeshStandardMaterial
    ['colormap.119']: THREE.MeshStandardMaterial
    ['colormap.120']: THREE.MeshStandardMaterial
    ['colormap.121']: THREE.MeshStandardMaterial
    ['colormap.122']: THREE.MeshStandardMaterial
    ['colormap.123']: THREE.MeshStandardMaterial
    ['colormap.124']: THREE.MeshStandardMaterial
    ['colormap.125']: THREE.MeshStandardMaterial
    ['colormap.126']: THREE.MeshStandardMaterial
    ['colormap.127']: THREE.MeshStandardMaterial
    ['colormap.128']: THREE.MeshStandardMaterial
    ['colormap.129']: THREE.MeshStandardMaterial
    ['colormap.130']: THREE.MeshStandardMaterial
    ['colormap.131']: THREE.MeshStandardMaterial
    ['colormap.132']: THREE.MeshStandardMaterial
    ['colormap.133']: THREE.MeshStandardMaterial
    ['colormap.134']: THREE.MeshStandardMaterial
    ['colormap.135']: THREE.MeshStandardMaterial
    ['colormap.136']: THREE.MeshStandardMaterial
    ['colormap.137']: THREE.MeshStandardMaterial
    ['colormap.138']: THREE.MeshStandardMaterial
    ['colormap.139']: THREE.MeshStandardMaterial
    ['colormap.140']: THREE.MeshStandardMaterial
    ['colormap.141']: THREE.MeshStandardMaterial
    ['colormap.142']: THREE.MeshStandardMaterial
    ['colormap.143']: THREE.MeshStandardMaterial
    ['colormap.007']: THREE.MeshStandardMaterial
    ['Tree_15_trunk_mat.001']: THREE.MeshStandardMaterial
    ['Tree_15_foliage_mat.001']: THREE.MeshStandardMaterial
    ['Tree_14_trunk_mat.001']: THREE.MeshStandardMaterial
    ['Tree_14_foliage_mat.001']: THREE.MeshStandardMaterial
    ['Tree_13_trunk_mat.001']: THREE.MeshStandardMaterial
    ['Tree_13_foliage_mat.001']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.001']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.001']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.002']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.002']: THREE.MeshStandardMaterial
    ['Tree_15_trunk_mat.002']: THREE.MeshStandardMaterial
    ['Tree_15_foliage_mat.002']: THREE.MeshStandardMaterial
    ['Tree_14_trunk_mat.002']: THREE.MeshStandardMaterial
    ['Tree_14_foliage_mat.002']: THREE.MeshStandardMaterial
    ['Tree_15_trunk_mat.003']: THREE.MeshStandardMaterial
    ['Tree_15_trunk_mat.004']: THREE.MeshStandardMaterial
    ['Tree_15_trunk_mat.005']: THREE.MeshStandardMaterial
    ['Tree_15_foliage_mat.003']: THREE.MeshStandardMaterial
    ['Tree_15_foliage_mat.004']: THREE.MeshStandardMaterial
    ['Tree_15_foliage_mat.005']: THREE.MeshStandardMaterial
    ['Tree_14_trunk_mat.003']: THREE.MeshStandardMaterial
    ['Tree_14_trunk_mat.004']: THREE.MeshStandardMaterial
    ['Tree_14_trunk_mat.005']: THREE.MeshStandardMaterial
    ['Tree_14_foliage_mat.003']: THREE.MeshStandardMaterial
    ['Tree_14_foliage_mat.004']: THREE.MeshStandardMaterial
    ['Tree_14_foliage_mat.005']: THREE.MeshStandardMaterial
    ['Tree_13_trunk_mat.002']: THREE.MeshStandardMaterial
    ['Tree_13_trunk_mat.003']: THREE.MeshStandardMaterial
    ['Tree_13_foliage_mat.002']: THREE.MeshStandardMaterial
    ['Tree_13_foliage_mat.003']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.003']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.004']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.005']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.003']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.004']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.005']: THREE.MeshStandardMaterial
    ['Tree_15_trunk_mat.006']: THREE.MeshStandardMaterial
    ['Tree_15_trunk_mat.007']: THREE.MeshStandardMaterial
    ['Tree_15_foliage_mat.006']: THREE.MeshStandardMaterial
    ['Tree_15_foliage_mat.007']: THREE.MeshStandardMaterial
    ['Tree_14_trunk_mat.006']: THREE.MeshStandardMaterial
    ['Tree_14_trunk_mat.007']: THREE.MeshStandardMaterial
    ['Tree_14_foliage_mat.006']: THREE.MeshStandardMaterial
    ['Tree_14_foliage_mat.007']: THREE.MeshStandardMaterial
    ['Tree_13_trunk_mat.004']: THREE.MeshStandardMaterial
    ['Tree_13_trunk_mat.005']: THREE.MeshStandardMaterial
    ['Tree_13_foliage_mat.004']: THREE.MeshStandardMaterial
    ['Tree_13_foliage_mat.005']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.006']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.007']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.008']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.006']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.007']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.008']: THREE.MeshStandardMaterial
    ['Tree_15_trunk_mat.009']: THREE.MeshStandardMaterial
    ['Tree_15_trunk_mat.010']: THREE.MeshStandardMaterial
    ['Tree_15_foliage_mat.009']: THREE.MeshStandardMaterial
    ['Tree_15_foliage_mat.010']: THREE.MeshStandardMaterial
    ['Tree_14_trunk_mat.009']: THREE.MeshStandardMaterial
    ['Tree_14_trunk_mat.010']: THREE.MeshStandardMaterial
    ['Tree_14_foliage_mat.009']: THREE.MeshStandardMaterial
    ['Tree_14_foliage_mat.010']: THREE.MeshStandardMaterial
    ['Tree_13_trunk_mat.006']: THREE.MeshStandardMaterial
    ['Tree_13_trunk_mat.007']: THREE.MeshStandardMaterial
    ['Tree_13_foliage_mat.006']: THREE.MeshStandardMaterial
    ['Tree_13_foliage_mat.007']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.009']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.010']: THREE.MeshStandardMaterial
    ['Tree_12_trunk_mat.011']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.009']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.010']: THREE.MeshStandardMaterial
    ['Tree_12_foliage_mat.011']: THREE.MeshStandardMaterial
    ['colormap.146']: THREE.MeshStandardMaterial
    ['colormap.148']: THREE.MeshStandardMaterial
    ['colormap.149']: THREE.MeshStandardMaterial
    ['colormap.150']: THREE.MeshStandardMaterial
    ['colormap.151']: THREE.MeshStandardMaterial
    ['colormap.152']: THREE.MeshStandardMaterial
    ['colormap.153']: THREE.MeshStandardMaterial
    ['colormap.002']: THREE.MeshStandardMaterial
    ['colormap.003']: THREE.MeshStandardMaterial
    ['colormap.004']: THREE.MeshStandardMaterial
    ['colormap.005']: THREE.MeshStandardMaterial
    ['colormap.006']: THREE.MeshStandardMaterial
    Building_1_mat: THREE.MeshStandardMaterial
    Building_2_mat: THREE.MeshStandardMaterial
    Building_3_mat: THREE.MeshStandardMaterial
    Building_4_mat: THREE.MeshStandardMaterial
    ['Grass_Material.001']: THREE.MeshStandardMaterial
    ['colormap.144']: THREE.MeshStandardMaterial
    ['colormap.145']: THREE.MeshStandardMaterial
    Tree_12_foliage_mat: THREE.MeshStandardMaterial
    Tree_12_trunk_mat: THREE.MeshStandardMaterial
    Tree_13_foliage_mat: THREE.MeshStandardMaterial
    Tree_13_trunk_mat: THREE.MeshStandardMaterial
    Tree_14_foliage_mat: THREE.MeshStandardMaterial
    Tree_14_trunk_mat: THREE.MeshStandardMaterial
    Tree_15_foliage_mat: THREE.MeshStandardMaterial
    Tree_15_trunk_mat: THREE.MeshStandardMaterial
    ['colormap.147']: THREE.MeshStandardMaterial
    Checkered: THREE.MeshStandardMaterial
    colormap: THREE.MeshStandardMaterial
    ['colormap.001']: THREE.MeshStandardMaterial
    ['colormap.008']: THREE.MeshStandardMaterial
    ['colormap.009']: THREE.MeshStandardMaterial
    ['colormap.010']: THREE.MeshStandardMaterial
    ['colormap.011']: THREE.MeshStandardMaterial
    ['colormap.012']: THREE.MeshStandardMaterial
    ['colormap.013']: THREE.MeshStandardMaterial
    ['colormap.014']: THREE.MeshStandardMaterial
    ['colormap.154']: THREE.MeshStandardMaterial
    ['colormap.155']: THREE.MeshStandardMaterial
    ['colormap.156']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function CarRacingMap(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/toy-car-racing.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['track-narrow'].geometry} material={materials['colormap.015']} />
      <mesh geometry={nodes['track-narrow-cap-back'].geometry} material={materials['colormap.016']} />
      <mesh geometry={nodes['track-narrow-cap-front'].geometry} material={materials['colormap.017']} />
      <mesh geometry={nodes['track-narrow-corner-large'].geometry} material={materials['colormap.018']} position={[18, 0, 0]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes['track-narrow-corner-large-ramp'].geometry} material={materials['colormap.019']} position={[-9.1, -0.032, 5.071]} />
      <mesh geometry={nodes['track-narrow-corner-large001'].geometry} material={materials['colormap.018']} />
      <mesh geometry={nodes['track-narrow-corner-large002'].geometry} material={materials['colormap.018']} />
      <mesh geometry={nodes['track-narrow-corner-small'].geometry} material={materials['colormap.020']} />
      <mesh geometry={nodes['track-narrow-corner-small-ramp'].geometry} material={materials['colormap.021']} />
      <mesh geometry={nodes['track-narrow-corner-small001'].geometry} material={materials['colormap.020']} />
      <mesh geometry={nodes['track-narrow-corner-small002'].geometry} material={materials['colormap.020']} />
      <mesh geometry={nodes['track-narrow-corner-small003'].geometry} material={materials['colormap.020']} />
      <mesh geometry={nodes['track-narrow-curve'].geometry} material={materials['colormap.022']} />
      <mesh geometry={nodes['track-narrow-looping'].geometry} material={materials['colormap.023']} position={[8.9, -0.032, 1.636]} />
      <mesh geometry={nodes['track-narrow-straight'].geometry} material={materials['colormap.024']} position={[3.953, -0.029, 14.303]} />
      <mesh geometry={nodes['track-narrow-straight-bend'].geometry} material={materials['colormap.025']} position={[-10.522, -0.032, -11.599]} />
      <mesh geometry={nodes['track-narrow-straight-bend-large'].geometry} material={materials['colormap.026']} position={[-1.133, -0.032, -12.271]} />
      <mesh geometry={nodes['track-narrow-straight-bump-down'].geometry} material={materials['colormap.027']} position={[-12.1, -0.032, 2.071]} />
      <mesh geometry={nodes['track-narrow-straight-bump-up'].geometry} material={materials['colormap.028']} position={[-9.1, -0.032, 1.449]} />
      <mesh geometry={nodes['track-narrow-straight-hill-beginning'].geometry} material={materials['colormap.029']} />
      <mesh geometry={nodes['track-narrow-straight-hill-complete'].geometry} material={materials['colormap.030']} />
      <mesh geometry={nodes['track-narrow-straight-hill-complete-half'].geometry} material={materials['colormap.031']} />
      <mesh geometry={nodes['track-narrow-straight-hill-end'].geometry} material={materials['colormap.032']} />
      <mesh geometry={nodes['track-narrow-straight-skew-left'].geometry} material={materials['colormap.033']} />
      <mesh geometry={nodes['track-narrow-straight-skew-left-side'].geometry} material={materials['colormap.034']} />
      <mesh geometry={nodes['track-narrow-straight-skew-right'].geometry} material={materials['colormap.035']} />
      <mesh geometry={nodes['track-narrow-straight-skew-right-side'].geometry} material={materials['colormap.036']} />
      <mesh geometry={nodes['track-narrow-straight001'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight002'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight003'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight004'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight005'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight006'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight007'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight008'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight009'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight010'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight011'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight012'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight013'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight014'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight015'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight016'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-narrow-straight017'].geometry} material={materials['colormap.024']} />
      <mesh geometry={nodes['track-road-narrow'].geometry} material={materials['colormap.037']} />
      <mesh geometry={nodes['track-road-narrow-cap-back'].geometry} material={materials['colormap.038']} />
      <mesh geometry={nodes['track-road-narrow-cap-front'].geometry} material={materials['colormap.039']} />
      <mesh geometry={nodes['track-road-narrow-corner-large'].geometry} material={materials['colormap.040']} position={[-3.1, -0.032, 0.882]} />
      <mesh geometry={nodes['track-road-narrow-corner-large-ramp'].geometry} material={materials['colormap.041']} />
      <mesh geometry={nodes['track-road-narrow-corner-small'].geometry} material={materials['colormap.042']} />
      <mesh geometry={nodes['track-road-narrow-corner-small-ramp'].geometry} material={materials['colormap.043']} position={[5.9, -0.032, 0.882]} />
      <mesh geometry={nodes['track-road-narrow-curve'].geometry} material={materials['colormap.044']} />
      <mesh geometry={nodes['track-road-narrow-looping'].geometry} material={materials['colormap.045']} />
      <mesh geometry={nodes['track-road-narrow-straight'].geometry} material={materials['colormap.046']} position={[-15.1, -0.032, -3.929]} />
      <mesh geometry={nodes['track-road-narrow-straight-bend'].geometry} material={materials['colormap.047']} position={[-12.1, -0.032, -3.929]} />
      <mesh geometry={nodes['track-road-narrow-straight-bend-large'].geometry} material={materials['colormap.048']} position={[-9.1, -0.032, -2.118]} />
      <mesh geometry={nodes['track-road-narrow-straight-bump-down'].geometry} material={materials['colormap.049']} position={[-6.1, -0.032, -2.118]} />
      <mesh geometry={nodes['track-road-narrow-straight-bump-up'].geometry} material={materials['colormap.050']} position={[-3.1, -0.032, -2.118]} />
      <mesh geometry={nodes['track-road-narrow-straight-hill-beginning'].geometry} material={materials['colormap.051']} position={[-0.1, -0.032, -2.118]} />
      <mesh geometry={nodes['track-road-narrow-straight-hill-complete'].geometry} material={materials['colormap.052']} position={[2.9, -0.032, -2.118]} />
      <mesh geometry={nodes['track-road-narrow-straight-hill-complete-half'].geometry} material={materials['colormap.053']} position={[5.9, -0.032, -2.118]} />
      <mesh geometry={nodes['track-road-narrow-straight-hill-end'].geometry} material={materials['colormap.054']} position={[8.9, -0.032, -2.118]} />
      <mesh geometry={nodes['track-road-narrow-straight-skew-left'].geometry} material={materials['colormap.055']} position={[-12.259, -0.032, -10.15]} />
      <mesh geometry={nodes['track-road-narrow-straight-skew-left-side'].geometry} material={materials['colormap.056']} />
      <mesh geometry={nodes['track-road-narrow-straight-skew-right'].geometry} material={materials['colormap.057']} />
      <mesh geometry={nodes['track-road-narrow-straight-skew-right-side'].geometry} material={materials['colormap.058']} />
      <mesh geometry={nodes['track-road-wide'].geometry} material={materials['colormap.059']} />
      <mesh geometry={nodes['track-road-wide-cap-back'].geometry} material={materials['colormap.060']} />
      <mesh geometry={nodes['track-road-wide-cap-front'].geometry} material={materials['colormap.061']} />
      <mesh geometry={nodes['track-road-wide-corner-large'].geometry} material={materials['colormap.062']} />
      <mesh geometry={nodes['track-road-wide-corner-large-ramp'].geometry} material={materials['colormap.063']} />
      <mesh geometry={nodes['track-road-wide-corner-small'].geometry} material={materials['colormap.064']} />
      <mesh geometry={nodes['track-road-wide-corner-small-ramp'].geometry} material={materials['colormap.065']} />
      <mesh geometry={nodes['track-road-wide-curve'].geometry} material={materials['colormap.066']} />
      <mesh geometry={nodes['track-road-wide-straight'].geometry} material={materials['colormap.067']} />
      <mesh geometry={nodes['track-road-wide-straight-bend'].geometry} material={materials['colormap.068']} />
      <mesh geometry={nodes['track-road-wide-straight-bend-large'].geometry} material={materials['colormap.069']} />
      <mesh geometry={nodes['track-road-wide-straight-bump-down'].geometry} material={materials['colormap.070']} />
      <mesh geometry={nodes['track-road-wide-straight-bump-up'].geometry} material={materials['colormap.071']} />
      <mesh geometry={nodes['track-road-wide-straight-hill-beginning'].geometry} material={materials['colormap.072']} />
      <mesh geometry={nodes['track-road-wide-straight-hill-complete'].geometry} material={materials['colormap.073']} />
      <mesh geometry={nodes['track-road-wide-straight-hill-complete-half'].geometry} material={materials['colormap.074']} />
      <mesh geometry={nodes['track-road-wide-straight-hill-end'].geometry} material={materials['colormap.075']} />
      <mesh geometry={nodes['track-road-wide-straight-skew-left'].geometry} material={materials['colormap.076']} />
      <mesh geometry={nodes['track-road-wide-straight-skew-left-side'].geometry} material={materials['colormap.077']} />
      <mesh geometry={nodes['track-road-wide-straight-skew-right'].geometry} material={materials['colormap.078']} />
      <mesh geometry={nodes['track-road-wide-straight-skew-right-side'].geometry} material={materials['colormap.079']} />
      <mesh geometry={nodes['track-striped-narrow'].geometry} material={materials['colormap.080']} />
      <mesh geometry={nodes['track-striped-narrow-cap-back'].geometry} material={materials['colormap.081']} />
      <mesh geometry={nodes['track-striped-narrow-cap-front'].geometry} material={materials['colormap.082']} />
      <mesh geometry={nodes['track-striped-narrow-corner-large'].geometry} material={materials['colormap.083']} position={[5.9, -0.032, -11.118]} />
      <mesh geometry={nodes['track-striped-narrow-corner-large-ramp'].geometry} material={materials['colormap.084']} position={[8.9, -0.032, -11.118]} />
      <mesh geometry={nodes['track-striped-narrow-corner-small-ramp'].geometry} material={materials['colormap.086']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small001'].geometry} material={materials['colormap.085']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small002'].geometry} material={materials['colormap.085']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small003'].geometry} material={materials['colormap.085']} />
      <mesh geometry={nodes['track-striped-narrow-curve'].geometry} material={materials['colormap.087']} />
      <mesh geometry={nodes['track-striped-narrow-looping'].geometry} material={materials['colormap.088']} />
      <mesh geometry={nodes['track-striped-narrow-straight'].geometry} material={materials['colormap.089']} position={[2.9, -0.032, -14.118]} />
      <mesh geometry={nodes['track-striped-narrow-straight-bend'].geometry} material={materials['colormap.090']} position={[5.9, -0.032, -14.118]} />
      <mesh geometry={nodes['track-striped-narrow-straight-bend-large'].geometry} material={materials['colormap.091']} position={[8.9, -0.032, -14.118]} />
      <mesh geometry={nodes['track-striped-narrow-straight-bump-down'].geometry} material={materials['colormap.092']} position={[-6.558, -0.032, -10.502]} />
      <mesh geometry={nodes['track-striped-narrow-straight-bump-up'].geometry} material={materials['colormap.093']} position={[-3.558, -0.032, -10.502]} />
      <mesh geometry={nodes['track-striped-narrow-straight-hill-beginning'].geometry} material={materials['colormap.094']} />
      <mesh geometry={nodes['track-striped-narrow-straight-hill-complete'].geometry} material={materials['colormap.095']} />
      <mesh geometry={nodes['track-striped-narrow-straight-hill-complete-half'].geometry} material={materials['colormap.096']} />
      <mesh geometry={nodes['track-striped-narrow-straight-hill-end'].geometry} material={materials['colormap.097']} />
      <mesh geometry={nodes['track-striped-narrow-straight-skew-left'].geometry} material={materials['colormap.098']} />
      <mesh geometry={nodes['track-striped-narrow-straight-skew-left-side'].geometry} material={materials['colormap.099']} />
      <mesh geometry={nodes['track-striped-narrow-straight-skew-right'].geometry} material={materials['colormap.100']} />
      <mesh geometry={nodes['track-striped-narrow-straight-skew-right-side'].geometry} material={materials['colormap.101']} />
      <mesh geometry={nodes['track-striped-narrow-straight001'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-straight002'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-straight003'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-straight004'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-straight005'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-straight006'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-straight007'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-straight008'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-straight009'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-straight010'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-straight011'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-wide'].geometry} material={materials['colormap.102']} />
      <mesh geometry={nodes['track-striped-wide-cap-back'].geometry} material={materials['colormap.103']} />
      <mesh geometry={nodes['track-striped-wide-cap-front'].geometry} material={materials['colormap.104']} />
      <mesh geometry={nodes['track-striped-wide-corner-large'].geometry} material={materials['colormap.105']} />
      <mesh geometry={nodes['track-striped-wide-corner-large-ramp'].geometry} material={materials['colormap.106']} />
      <mesh geometry={nodes['track-striped-wide-corner-small'].geometry} material={materials['colormap.107']} />
      <mesh geometry={nodes['track-striped-wide-corner-small-ramp'].geometry} material={materials['colormap.108']} />
      <mesh geometry={nodes['track-striped-wide-curve'].geometry} material={materials['colormap.109']} />
      <mesh geometry={nodes['track-striped-wide-straight'].geometry} material={materials['colormap.110']} />
      <mesh geometry={nodes['track-striped-wide-straight-bend'].geometry} material={materials['colormap.111']} />
      <mesh geometry={nodes['track-striped-wide-straight-bend-large'].geometry} material={materials['colormap.112']} />
      <mesh geometry={nodes['track-striped-wide-straight-bump-down'].geometry} material={materials['colormap.113']} />
      <mesh geometry={nodes['track-striped-wide-straight-bump-up'].geometry} material={materials['colormap.114']} />
      <mesh geometry={nodes['track-striped-wide-straight-hill-beginning'].geometry} material={materials['colormap.115']} />
      <mesh geometry={nodes['track-striped-wide-straight-hill-complete'].geometry} material={materials['colormap.116']} />
      <mesh geometry={nodes['track-striped-wide-straight-hill-complete-half'].geometry} material={materials['colormap.117']} />
      <mesh geometry={nodes['track-striped-wide-straight-hill-end'].geometry} material={materials['colormap.118']} />
      <mesh geometry={nodes['track-striped-wide-straight-skew-left'].geometry} material={materials['colormap.119']} />
      <mesh geometry={nodes['track-striped-wide-straight-skew-left-side'].geometry} material={materials['colormap.120']} />
      <mesh geometry={nodes['track-striped-wide-straight-skew-right'].geometry} material={materials['colormap.121']} />
      <mesh geometry={nodes['track-striped-wide-straight-skew-right-side'].geometry} material={materials['colormap.122']} />
      <mesh geometry={nodes['track-wide'].geometry} material={materials['colormap.123']} />
      <mesh geometry={nodes['track-wide-cap-back'].geometry} material={materials['colormap.124']} />
      <mesh geometry={nodes['track-wide-cap-front'].geometry} material={materials['colormap.125']} />
      <mesh geometry={nodes['track-wide-corner-large'].geometry} material={materials['colormap.126']} />
      <mesh geometry={nodes['track-wide-corner-large-ramp'].geometry} material={materials['colormap.127']} />
      <mesh geometry={nodes['track-wide-corner-small'].geometry} material={materials['colormap.128']} />
      <mesh geometry={nodes['track-wide-corner-small-ramp'].geometry} material={materials['colormap.129']} />
      <mesh geometry={nodes['track-wide-curve'].geometry} material={materials['colormap.130']} />
      <mesh geometry={nodes['track-wide-straight'].geometry} material={materials['colormap.131']} />
      <mesh geometry={nodes['track-wide-straight-bend'].geometry} material={materials['colormap.132']} />
      <mesh geometry={nodes['track-wide-straight-bend-large'].geometry} material={materials['colormap.133']} />
      <mesh geometry={nodes['track-wide-straight-bump-down'].geometry} material={materials['colormap.134']} />
      <mesh geometry={nodes['track-wide-straight-bump-up'].geometry} material={materials['colormap.135']} />
      <mesh geometry={nodes['track-wide-straight-hill-beginning'].geometry} material={materials['colormap.136']} />
      <mesh geometry={nodes['track-wide-straight-hill-complete'].geometry} material={materials['colormap.137']} />
      <mesh geometry={nodes['track-wide-straight-hill-complete-half'].geometry} material={materials['colormap.138']} />
      <mesh geometry={nodes['track-wide-straight-hill-end'].geometry} material={materials['colormap.139']} />
      <mesh geometry={nodes['track-wide-straight-skew-left'].geometry} material={materials['colormap.140']} />
      <mesh geometry={nodes['track-wide-straight-skew-left-side'].geometry} material={materials['colormap.141']} />
      <mesh geometry={nodes['track-wide-straight-skew-right'].geometry} material={materials['colormap.142']} />
      <mesh geometry={nodes['track-wide-straight-skew-right-side'].geometry} material={materials['colormap.143']} />
      <mesh geometry={nodes['item-cone043'].geometry} material={materials['colormap.007']} position={[-2, 0.3, 5]} scale={0.8} />
      <mesh geometry={nodes['item-cone044'].geometry} material={materials['colormap.007']} position={[-2, 0.3, 3]} scale={0.8} />
      <mesh geometry={nodes['item-cone045'].geometry} material={materials['colormap.007']} position={[-2, 0.3, 1]} scale={0.8} />
      <mesh geometry={nodes['item-cone046'].geometry} material={materials['colormap.007']} position={[12, 0.3, 7]} scale={0.8} />
      <mesh geometry={nodes['item-cone047'].geometry} material={materials['colormap.007']} position={[12, 0.3, 5]} scale={0.8} />
      <mesh geometry={nodes['item-cone048'].geometry} material={materials['colormap.007']} position={[12, 0.3, 3]} scale={0.8} />
      <mesh geometry={nodes['item-cone049'].geometry} material={materials['colormap.007']} position={[12, 0.3, 1]} scale={0.8} />
      <mesh geometry={nodes['item-cone050'].geometry} material={materials['colormap.007']} position={[12, 0.3, -1]} scale={0.8} />
      <mesh geometry={nodes['item-cone051'].geometry} material={materials['colormap.007']} position={[1, 0.3, -4]} scale={0.8} />
      <mesh geometry={nodes['item-cone052'].geometry} material={materials['colormap.007']} position={[3, 0.3, -4]} scale={0.8} />
      <mesh geometry={nodes['item-cone053'].geometry} material={materials['colormap.007']} position={[5, 0.3, -4]} scale={0.8} />
      <mesh geometry={nodes['item-cone054'].geometry} material={materials['colormap.007']} position={[7, 0.3, -4]} scale={0.8} />
      <mesh geometry={nodes['item-cone055'].geometry} material={materials['colormap.007']} position={[9, 0.3, -4]} scale={0.8} />
      <mesh geometry={nodes['item-cone056'].geometry} material={materials['colormap.007']} position={[11, 0.3, -4]} scale={0.8} />
      <mesh geometry={nodes['item-cone057'].geometry} material={materials['colormap.007']} position={[2, 0.3, 4]} scale={0.8} />
      <mesh geometry={nodes['item-cone058'].geometry} material={materials['colormap.007']} position={[4, 0.3, 4]} scale={0.8} />
      <mesh geometry={nodes['item-cone059'].geometry} material={materials['colormap.007']} position={[6, 0.3, 4]} scale={0.8} />
      <mesh geometry={nodes['item-cone060'].geometry} material={materials['colormap.007']} position={[8, 0.3, 2]} scale={0.8} />
      <mesh geometry={nodes['item-cone061'].geometry} material={materials['colormap.007']} position={[8, 0.3, 0]} scale={0.8} />
      <mesh geometry={nodes['item-cone062'].geometry} material={materials['colormap.007']} position={[4, 0.3, 0]} scale={0.8} />
      <mesh geometry={nodes['item-cone063'].geometry} material={materials['colormap.007']} position={[6, 0.3, 0]} scale={0.8} />
      <mesh geometry={nodes['item-cone064'].geometry} material={materials['colormap.007']} position={[-4, 0.3, 6]} scale={0.7} />
      <mesh geometry={nodes['item-cone065'].geometry} material={materials['colormap.007']} position={[-4, 0.3, 4]} scale={0.7} />
      <mesh geometry={nodes['item-cone066'].geometry} material={materials['colormap.007']} position={[-4, 0.3, 2]} scale={0.7} />
      <mesh geometry={nodes['item-cone067'].geometry} material={materials['colormap.007']} position={[-4, 0.3, 0]} scale={0.7} />
      <mesh geometry={nodes['item-cone068'].geometry} material={materials['colormap.007']} position={[-4, 0.3, -2]} scale={0.7} />
      <mesh geometry={nodes['item-cone069'].geometry} material={materials['colormap.007']} position={[-4, 0.3, -4]} scale={0.7} />
      <mesh geometry={nodes['item-cone070'].geometry} material={materials['colormap.007']} position={[-4, 0.3, -6]} scale={0.7} />
      <mesh geometry={nodes['item-cone071'].geometry} material={materials['colormap.007']} position={[-4, 0.3, -8]} scale={0.7} />
      <mesh geometry={nodes['item-cone072'].geometry} material={materials['colormap.007']} position={[14, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes['item-cone073'].geometry} material={materials['colormap.007']} position={[14, 0.3, 6]} scale={0.7} />
      <mesh geometry={nodes['item-cone074'].geometry} material={materials['colormap.007']} position={[14, 0.3, 4]} scale={0.7} />
      <mesh geometry={nodes['item-cone075'].geometry} material={materials['colormap.007']} position={[14, 0.3, 2]} scale={0.7} />
      <mesh geometry={nodes['item-cone076'].geometry} material={materials['colormap.007']} position={[14, 0.3, 0]} scale={0.7} />
      <mesh geometry={nodes['item-cone077'].geometry} material={materials['colormap.007']} position={[14, 0.3, -2]} scale={0.7} />
      <mesh geometry={nodes['item-cone078'].geometry} material={materials['colormap.007']} position={[14, 0.3, -4]} scale={0.7} />
      <mesh geometry={nodes['item-cone079'].geometry} material={materials['colormap.007']} position={[14, 0.3, -6]} scale={0.7} />
      <mesh geometry={nodes['item-cone080'].geometry} material={materials['colormap.007']} position={[14, 0.3, -8]} scale={0.7} />
      <mesh geometry={nodes['item-cone081'].geometry} material={materials['colormap.007']} position={[-4, 0.3, -10]} scale={0.7} />
      <mesh geometry={nodes['item-cone082'].geometry} material={materials['colormap.007']} position={[-2, 0.3, -10]} scale={0.7} />
      <mesh geometry={nodes['item-cone083'].geometry} material={materials['colormap.007']} position={[0, 0.3, -10]} scale={0.7} />
      <mesh geometry={nodes['item-cone084'].geometry} material={materials['colormap.007']} position={[2, 0.3, -10]} scale={0.7} />
      <mesh geometry={nodes['item-cone085'].geometry} material={materials['colormap.007']} position={[4, 0.3, -10]} scale={0.7} />
      <mesh geometry={nodes['item-cone086'].geometry} material={materials['colormap.007']} position={[6, 0.3, -10]} scale={0.7} />
      <mesh geometry={nodes['item-cone087'].geometry} material={materials['colormap.007']} position={[8, 0.3, -10]} scale={0.7} />
      <mesh geometry={nodes['item-cone088'].geometry} material={materials['colormap.007']} position={[10, 0.3, -10]} scale={0.7} />
      <mesh geometry={nodes['item-cone089'].geometry} material={materials['colormap.007']} position={[12, 0.3, -10]} scale={0.7} />
      <mesh geometry={nodes['item-cone090'].geometry} material={materials['colormap.007']} position={[-4, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes['item-cone091'].geometry} material={materials['colormap.007']} position={[-2, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes['item-cone092'].geometry} material={materials['colormap.007']} position={[0, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes['item-cone093'].geometry} material={materials['colormap.007']} position={[2, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes['item-cone094'].geometry} material={materials['colormap.007']} position={[4, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes['item-cone095'].geometry} material={materials['colormap.007']} position={[6, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes['item-cone096'].geometry} material={materials['colormap.007']} position={[8, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes['item-cone097'].geometry} material={materials['colormap.007']} position={[10, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes['item-cone098'].geometry} material={materials['colormap.007']} position={[12, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes['item-cone099'].geometry} material={materials['colormap.007']} position={[2, 0.3, -2]} scale={0.7} />
      <mesh geometry={nodes['item-cone100'].geometry} material={materials['colormap.007']} position={[2, 0.3, -4]} scale={0.7} />
      <mesh geometry={nodes['item-cone101'].geometry} material={materials['colormap.007']} position={[2, 0.3, -6]} scale={0.7} />
      <mesh geometry={nodes['item-cone102'].geometry} material={materials['colormap.007']} position={[10, 0.3, -2]} scale={0.7} />
      <mesh geometry={nodes['item-cone103'].geometry} material={materials['colormap.007']} position={[10, 0.3, -4]} scale={0.7} />
      <mesh geometry={nodes['item-cone'].geometry} material={materials['colormap.007']} position={[-4, 0.3, 8]} scale={0.7} />
      <mesh geometry={nodes.Tree_15_trunk001.geometry} material={materials['Tree_15_trunk_mat.001']} position={[-14.122, -0.295, 6.638]} />
      <mesh geometry={nodes.Tree_15_foliage001.geometry} material={materials['Tree_15_foliage_mat.001']} position={[-14.122, -0.295, 6.638]} />
      <mesh geometry={nodes.Tree_14_trunk001.geometry} material={materials['Tree_14_trunk_mat.001']} position={[-14.122, -0.295, 6.638]} />
      <mesh geometry={nodes.Tree_14_foliage001.geometry} material={materials['Tree_14_foliage_mat.001']} position={[-14.122, -0.295, 6.638]} />
      <mesh geometry={nodes.Tree_13_trunk001.geometry} material={materials['Tree_13_trunk_mat.001']} position={[-14.122, -0.295, 6.638]} />
      <mesh geometry={nodes.Tree_13_foliage001.geometry} material={materials['Tree_13_foliage_mat.001']} position={[-14.122, -0.295, 6.638]} />
      <mesh geometry={nodes.Tree_12_trunk001.geometry} material={materials['Tree_12_trunk_mat.001']} position={[-14.122, -0.295, 6.638]} />
      <mesh geometry={nodes.Tree_12_foliage001.geometry} material={materials['Tree_12_foliage_mat.001']} position={[-14.122, -0.295, 6.638]} />
      <mesh geometry={nodes.Tree_12_trunk002.geometry} material={materials['Tree_12_trunk_mat.002']} position={[-17.323, -0.196, 6.816]} />
      <mesh geometry={nodes.Tree_12_foliage002.geometry} material={materials['Tree_12_foliage_mat.002']} position={[-17.323, -0.196, 6.816]} />
      <mesh geometry={nodes.Tree_15_trunk002.geometry} material={materials['Tree_15_trunk_mat.002']} position={[8.994, -0.204, 7.329]} />
      <mesh geometry={nodes.Tree_15_foliage002.geometry} material={materials['Tree_15_foliage_mat.002']} position={[8.994, -0.204, 7.329]} />
      <mesh geometry={nodes.Tree_14_trunk002.geometry} material={materials['Tree_14_trunk_mat.002']} position={[9.66, -0.204, 6.964]} />
      <mesh geometry={nodes.Tree_14_foliage002.geometry} material={materials['Tree_14_foliage_mat.002']} position={[9.66, -0.204, 6.964]} />
      <mesh geometry={nodes.Tree_15_trunk003.geometry} material={materials['Tree_15_trunk_mat.003']} position={[9.66, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_15_trunk004.geometry} material={materials['Tree_15_trunk_mat.004']} position={[-14.122, -0.295, -31.104]} />
      <mesh geometry={nodes.Tree_15_trunk005.geometry} material={materials['Tree_15_trunk_mat.005']} position={[2.033, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_15_foliage003.geometry} material={materials['Tree_15_foliage_mat.003']} position={[9.66, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_15_foliage004.geometry} material={materials['Tree_15_foliage_mat.004']} position={[-14.122, -0.295, -31.104]} />
      <mesh geometry={nodes.Tree_15_foliage005.geometry} material={materials['Tree_15_foliage_mat.005']} position={[2.033, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_14_trunk003.geometry} material={materials['Tree_14_trunk_mat.003']} position={[9.66, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_14_trunk004.geometry} material={materials['Tree_14_trunk_mat.004']} position={[-14.122, -0.295, -31.104]} />
      <mesh geometry={nodes.Tree_14_trunk005.geometry} material={materials['Tree_14_trunk_mat.005']} position={[2.033, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_14_foliage003.geometry} material={materials['Tree_14_foliage_mat.003']} position={[9.66, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_14_foliage004.geometry} material={materials['Tree_14_foliage_mat.004']} position={[-14.122, -0.295, -31.104]} />
      <mesh geometry={nodes.Tree_14_foliage005.geometry} material={materials['Tree_14_foliage_mat.005']} position={[2.033, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_13_trunk002.geometry} material={materials['Tree_13_trunk_mat.002']} position={[-14.122, -0.295, -31.104]} />
      <mesh geometry={nodes.Tree_13_trunk003.geometry} material={materials['Tree_13_trunk_mat.003']} position={[2.033, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_13_foliage002.geometry} material={materials['Tree_13_foliage_mat.002']} position={[-14.122, -0.295, -31.104]} />
      <mesh geometry={nodes.Tree_13_foliage003.geometry} material={materials['Tree_13_foliage_mat.003']} position={[2.033, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_12_trunk003.geometry} material={materials['Tree_12_trunk_mat.003']} position={[-17.323, -0.196, -30.926]} />
      <mesh geometry={nodes.Tree_12_trunk004.geometry} material={materials['Tree_12_trunk_mat.004']} position={[-14.122, -0.295, -31.104]} />
      <mesh geometry={nodes.Tree_12_trunk005.geometry} material={materials['Tree_12_trunk_mat.005']} position={[2.033, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_12_foliage003.geometry} material={materials['Tree_12_foliage_mat.003']} position={[-17.323, -0.196, -30.926]} />
      <mesh geometry={nodes.Tree_12_foliage004.geometry} material={materials['Tree_12_foliage_mat.004']} position={[-14.122, -0.295, -31.104]} />
      <mesh geometry={nodes.Tree_12_foliage005.geometry} material={materials['Tree_12_foliage_mat.005']} position={[2.033, -0.204, -30.778]} />
      <mesh geometry={nodes.Tree_15_trunk006.geometry} material={materials['Tree_15_trunk_mat.006']} position={[7.262, -0.204, -6.016]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_15_trunk007.geometry} material={materials['Tree_15_trunk_mat.007']} position={[6.887, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_15_foliage006.geometry} material={materials['Tree_15_foliage_mat.006']} position={[7.262, -0.204, -6.016]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_15_foliage007.geometry} material={materials['Tree_15_foliage_mat.007']} position={[6.887, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_14_trunk006.geometry} material={materials['Tree_14_trunk_mat.006']} position={[7.262, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_14_trunk007.geometry} material={materials['Tree_14_trunk_mat.007']} position={[6.887, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_14_foliage006.geometry} material={materials['Tree_14_foliage_mat.006']} position={[7.262, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_14_foliage007.geometry} material={materials['Tree_14_foliage_mat.007']} position={[6.887, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_13_trunk004.geometry} material={materials['Tree_13_trunk_mat.004']} position={[7.262, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_13_trunk005.geometry} material={materials['Tree_13_trunk_mat.005']} position={[6.887, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_13_foliage004.geometry} material={materials['Tree_13_foliage_mat.004']} position={[7.262, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_13_foliage005.geometry} material={materials['Tree_13_foliage_mat.005']} position={[6.887, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_trunk006.geometry} material={materials['Tree_12_trunk_mat.006']} position={[7.262, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_trunk007.geometry} material={materials['Tree_12_trunk_mat.007']} position={[6.887, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_trunk008.geometry} material={materials['Tree_12_trunk_mat.008']} position={[6.933, -0.196, 13.494]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_foliage006.geometry} material={materials['Tree_12_foliage_mat.006']} position={[7.262, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_foliage007.geometry} material={materials['Tree_12_foliage_mat.007']} position={[6.887, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_foliage008.geometry} material={materials['Tree_12_foliage_mat.008']} position={[6.933, -0.196, 13.494]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_15_trunk008.geometry} material={materials['Tree_15_trunk_mat.009']} position={[-31.126, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_15_trunk009.geometry} material={materials['Tree_15_trunk_mat.010']} position={[-30.752, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_15_foliage008.geometry} material={materials['Tree_15_foliage_mat.009']} position={[-31.126, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_15_foliage009.geometry} material={materials['Tree_15_foliage_mat.010']} position={[-30.752, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_14_trunk008.geometry} material={materials['Tree_14_trunk_mat.009']} position={[-31.126, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_14_trunk009.geometry} material={materials['Tree_14_trunk_mat.010']} position={[-30.752, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_14_foliage008.geometry} material={materials['Tree_14_foliage_mat.009']} position={[-31.126, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_14_foliage009.geometry} material={materials['Tree_14_foliage_mat.010']} position={[-30.752, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_13_trunk006.geometry} material={materials['Tree_13_trunk_mat.006']} position={[-31.126, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_13_trunk007.geometry} material={materials['Tree_13_trunk_mat.007']} position={[-30.752, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_13_foliage006.geometry} material={materials['Tree_13_foliage_mat.006']} position={[-31.126, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_13_foliage007.geometry} material={materials['Tree_13_foliage_mat.007']} position={[-30.752, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_trunk009.geometry} material={materials['Tree_12_trunk_mat.009']} position={[-31.08, -0.196, 13.494]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_trunk010.geometry} material={materials['Tree_12_trunk_mat.010']} position={[-31.126, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_trunk011.geometry} material={materials['Tree_12_trunk_mat.011']} position={[-30.752, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_foliage009.geometry} material={materials['Tree_12_foliage_mat.009']} position={[-31.08, -0.196, 13.494]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_foliage010.geometry} material={materials['Tree_12_foliage_mat.010']} position={[-31.126, -0.295, 9.612]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes.Tree_12_foliage011.geometry} material={materials['Tree_12_foliage_mat.011']} position={[-30.752, -0.204, -6.516]} rotation={[0, 1.529, 0]} />
      <mesh geometry={nodes['vehicle-drag-racer'].geometry} material={materials['colormap.146']} position={[12, 0.3, -2]}>
        <mesh geometry={nodes['wheel-bl'].geometry} material={materials['colormap.146']} position={[1.784, 0.656, 10.456]} />
        <mesh geometry={nodes['wheel-br'].geometry} material={materials['colormap.146']} position={[2.216, 0.656, 10.456]} />
        <mesh geometry={nodes['wheel-fl'].geometry} material={materials['colormap.146']} position={[1.8, 0.625, 9.631]} />
        <mesh geometry={nodes['wheel-fr'].geometry} material={materials['colormap.146']} position={[2.2, 0.625, 9.631]} />
      </mesh>
      <mesh geometry={nodes['vehicle-racer'].geometry} material={materials['colormap.148']} position={[-1, 0.3, -1]}>
        <mesh geometry={nodes['wheel-bl002'].geometry} material={materials['colormap.148']} position={[-2.188, 0.625, 8.25]} />
        <mesh geometry={nodes['wheel-br002'].geometry} material={materials['colormap.148']} position={[-1.813, 0.625, 8.25]} />
        <mesh geometry={nodes['wheel-fl002'].geometry} material={materials['colormap.148']} position={[-2.188, 0.625, 7.75]} />
        <mesh geometry={nodes['wheel-fr002'].geometry} material={materials['colormap.148']} position={[-1.813, 0.625, 7.75]} />
      </mesh>
      <mesh geometry={nodes['vehicle-racer-low'].geometry} material={materials['colormap.149']} position={[5, 0.5, 0]}>
        <mesh geometry={nodes['wheel-bl003'].geometry} material={materials['colormap.149']} position={[-0.188, 0.125, 0.25]} />
        <mesh geometry={nodes['wheel-br003'].geometry} material={materials['colormap.149']} position={[0.188, 0.125, 0.25]} />
        <mesh geometry={nodes['wheel-fl003'].geometry} material={materials['colormap.149']} position={[-0.188, 0.125, -0.25]} />
        <mesh geometry={nodes['wheel-fr003'].geometry} material={materials['colormap.149']} position={[0.188, 0.125, -0.25]} />
      </mesh>
      <mesh geometry={nodes['vehicle-speedster'].geometry} material={materials['colormap.150']} position={[1, 0.3, -1]}>
        <mesh geometry={nodes['wheel-bl004'].geometry} material={materials['colormap.150']} position={[1.787, 0.625, 8.313]} />
        <mesh geometry={nodes['wheel-br004'].geometry} material={materials['colormap.150']} position={[2.213, 0.625, 8.313]} />
        <mesh geometry={nodes['wheel-fl004'].geometry} material={materials['colormap.150']} position={[1.787, 0.625, 7.813]} />
        <mesh geometry={nodes['wheel-fr004'].geometry} material={materials['colormap.150']} position={[2.213, 0.625, 7.813]} />
      </mesh>
      <mesh geometry={nodes['vehicle-suv'].geometry} material={materials['colormap.151']} position={[6, 0.3, -8]}>
        <mesh geometry={nodes['wheel-bl005'].geometry} material={materials['colormap.151']} position={[-2.188, 0.625, 10.25]} />
        <mesh geometry={nodes['wheel-br005'].geometry} material={materials['colormap.151']} position={[-1.813, 0.625, 10.25]} />
        <mesh geometry={nodes['wheel-fl005'].geometry} material={materials['colormap.151']} position={[-2.188, 0.625, 9.75]} />
        <mesh geometry={nodes['wheel-fr005'].geometry} material={materials['colormap.151']} position={[-1.813, 0.625, 9.75]} />
      </mesh>
      <mesh geometry={nodes['vehicle-truck'].geometry} material={materials['colormap.152']} position={[6, 0.3, 6]}>
        <mesh geometry={nodes['wheel-bl006'].geometry} material={materials['colormap.152']} position={[-0.188, 0.125, 0.256]} />
        <mesh geometry={nodes['wheel-br006'].geometry} material={materials['colormap.152']} position={[0.188, 0.125, 0.256]} />
        <mesh geometry={nodes['wheel-fl006'].geometry} material={materials['colormap.152']} position={[-0.188, 0.125, -0.244]} />
        <mesh geometry={nodes['wheel-fr006'].geometry} material={materials['colormap.152']} position={[0.188, 0.125, -0.244]} />
      </mesh>
      <mesh geometry={nodes['vehicle-vintage-racer'].geometry} material={materials['colormap.153']} position={[0, 0.3, 4]}>
        <mesh geometry={nodes['wheel-bl007'].geometry} material={materials['colormap.153']} position={[-0.212, 0.125, 0.25]} />
        <mesh geometry={nodes['wheel-br007'].geometry} material={materials['colormap.153']} position={[0.212, 0.125, 0.25]} />
        <mesh geometry={nodes['wheel-fl007'].geometry} material={materials['colormap.153']} position={[-0.212, 0.125, -0.25]} />
        <mesh geometry={nodes['wheel-fr007'].geometry} material={materials['colormap.153']} position={[0.212, 0.125, -0.25]} />
      </mesh>
      <mesh geometry={nodes['item-banana'].geometry} material={materials['colormap.002']} position={[11.033, 0.096, 11.964]} />
      <mesh geometry={nodes['item-box'].geometry} material={materials['colormap.003']} position={[5, 0.5, 2]} />
      <mesh geometry={nodes['item-coin-bronze'].geometry} material={materials['colormap.004']} position={[10, 0.5, 2]} />
      <mesh geometry={nodes['item-coin-gold'].geometry} material={materials['colormap.005']} position={[8, 0.5, -2]} />
      <mesh geometry={nodes['item-coin-silver'].geometry} material={materials['colormap.006']} position={[4, 0.5, -2]} />
      <mesh geometry={nodes['item-cone001'].geometry} material={materials['colormap.007']} position={[12, 0.3, -2]} />
      <mesh geometry={nodes['item-cone002'].geometry} material={materials['colormap.007']} position={[12, 0.3, 2]} />
      <mesh geometry={nodes['item-cone003'].geometry} material={materials['colormap.007']} position={[-12, 0.3, 0]} />
      <mesh geometry={nodes['item-cone004'].geometry} material={materials['colormap.007']} position={[-12, 0.3, -2]} />
      <mesh geometry={nodes['item-cone005'].geometry} material={materials['colormap.007']} position={[-12, 0.3, 2]} />
      <mesh geometry={nodes['item-cone006'].geometry} material={materials['colormap.007']} position={[0, 0.3, -10]} />
      <mesh geometry={nodes['item-cone007'].geometry} material={materials['colormap.007']} position={[2, 0.3, -10]} />
      <mesh geometry={nodes['item-cone008'].geometry} material={materials['colormap.007']} position={[-2, 0.3, -10]} />
      <mesh geometry={nodes['item-cone009'].geometry} material={materials['colormap.007']} position={[10, 0.3, 3]} />
      <mesh geometry={nodes['item-cone010'].geometry} material={materials['colormap.007']} position={[10, 0.3, 0]} />
      <mesh geometry={nodes['item-cone011'].geometry} material={materials['colormap.007']} position={[10, 0.3, -3]} />
      <mesh geometry={nodes['item-cone012'].geometry} material={materials['colormap.007']} position={[10, 0.3, -6]} />
      <mesh geometry={nodes['item-cone013'].geometry} material={materials['colormap.007']} position={[-10, 0.3, 6]} />
      <mesh geometry={nodes['item-cone014'].geometry} material={materials['colormap.007']} position={[-10, 0.3, 3]} />
      <mesh geometry={nodes['item-cone015'].geometry} material={materials['colormap.007']} position={[-10, 0.3, 0]} />
      <mesh geometry={nodes['item-cone016'].geometry} material={materials['colormap.007']} position={[-10, 0.3, -3]} />
      <mesh geometry={nodes['item-cone017'].geometry} material={materials['colormap.007']} position={[-10, 0.3, -6]} />
      <mesh geometry={nodes['item-cone018'].geometry} material={materials['colormap.007']} position={[3, 0.3, 2]} />
      <mesh geometry={nodes['item-cone019'].geometry} material={materials['colormap.007']} position={[3, 0.3, -2]} />
      <mesh geometry={nodes['item-cone020'].geometry} material={materials['colormap.007']} position={[-3, 0.3, 2]} />
      <mesh geometry={nodes['item-cone021'].geometry} material={materials['colormap.007']} position={[-3, 0.3, -2]} />
      <mesh geometry={nodes['item-cone022'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone023'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone024'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone025'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone026'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone027'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone028'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone029'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone030'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone031'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone032'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone033'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone034'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone035'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone036'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone037'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone038'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone039'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone040'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone041'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes['item-cone042'].geometry} material={materials['colormap.007']} />
      <mesh geometry={nodes.Building_1.geometry} material={materials.Building_1_mat} />
      <mesh geometry={nodes.Building_2.geometry} material={materials.Building_2_mat} />
      <mesh geometry={nodes.Building_3.geometry} material={materials.Building_3_mat} />
      <mesh geometry={nodes.Building_4.geometry} material={materials.Building_4_mat} />
      <mesh geometry={nodes.Ground_Plane001.geometry} material={materials['Grass_Material.001']} scale={[1.02, 1, 1]} />
      <mesh geometry={nodes.tree.geometry} material={materials['colormap.144']} />
      <mesh geometry={nodes['tree-pine'].geometry} material={materials['colormap.145']} />
      <mesh geometry={nodes.Tree_12_foliage.geometry} material={materials.Tree_12_foliage_mat} position={[2.033, -0.204, 6.964]} />
      <mesh geometry={nodes.Tree_12_trunk.geometry} material={materials.Tree_12_trunk_mat} position={[2.033, -0.204, 6.964]} />
      <mesh geometry={nodes.Tree_13_foliage.geometry} material={materials.Tree_13_foliage_mat} position={[2.033, -0.204, 6.964]} />
      <mesh geometry={nodes.Tree_13_trunk.geometry} material={materials.Tree_13_trunk_mat} position={[2.033, -0.204, 6.964]} />
      <mesh geometry={nodes.Tree_14_foliage.geometry} material={materials.Tree_14_foliage_mat} position={[2.033, -0.204, 6.964]} />
      <mesh geometry={nodes.Tree_14_trunk.geometry} material={materials.Tree_14_trunk_mat} position={[2.033, -0.204, 6.964]} />
      <mesh geometry={nodes.Tree_15_foliage.geometry} material={materials.Tree_15_foliage_mat} position={[2.033, -0.204, 6.964]} />
      <mesh geometry={nodes.Tree_15_trunk.geometry} material={materials.Tree_15_trunk_mat} position={[2.033, -0.204, 6.964]} />
      <mesh geometry={nodes.body.geometry} material={materials['colormap.147']} position={[0, 0.156, 0]} />
      <mesh geometry={nodes.Finish_Line.geometry} material={materials.Checkered} position={[0, 0.01, 6]} scale={[4, 1, 0.2]} />
      <mesh geometry={nodes.gate.geometry} material={materials.colormap} position={[-1, 0, 1]} scale={1.2} />
      <mesh geometry={nodes['gate-finish'].geometry} material={materials['colormap.001']} position={[1, 0, 1]} scale={1.2} />
      <mesh geometry={nodes.smoke.geometry} material={materials['colormap.008']} position={[-8, 0.5, 10]} scale={0.5} />
      <mesh geometry={nodes.supports.geometry} material={materials['colormap.009']} position={[-15, 0, 5]} scale={2} />
      <mesh geometry={nodes['supports-clamp'].geometry} material={materials['colormap.010']} />
      <mesh geometry={nodes['supports-diagonal'].geometry} material={materials['colormap.011']} />
      <mesh geometry={nodes['supports-wide'].geometry} material={materials['colormap.012']} />
      <mesh geometry={nodes['supports-wide-clamp'].geometry} material={materials['colormap.013']} />
      <mesh geometry={nodes['supports-wide-diagonal'].geometry} material={materials['colormap.014']} />
      <mesh geometry={nodes.supports001.geometry} material={materials['colormap.009']} position={[-15, 0, 0]} scale={2} />
      <mesh geometry={nodes.supports002.geometry} material={materials['colormap.009']} position={[-15, 0, -5]} scale={2} />
      <mesh geometry={nodes.supports003.geometry} material={materials['colormap.009']} position={[15, 0, 5]} scale={2} />
      <mesh geometry={nodes.supports004.geometry} material={materials['colormap.009']} position={[15, 0, 0]} scale={2} />
      <mesh geometry={nodes.supports005.geometry} material={materials['colormap.009']} position={[15, 0, -5]} scale={2} />
      <mesh geometry={nodes['wheel-bl001'].geometry} material={materials['colormap.147']} position={[-0.219, 0.188, 0.25]} />
      <mesh geometry={nodes['wheel-br001'].geometry} material={materials['colormap.147']} position={[0.219, 0.188, 0.25]} />
      <mesh geometry={nodes['wheel-fl001'].geometry} material={materials['colormap.147']} position={[-0.219, 0.188, -0.25]} />
      <mesh geometry={nodes['wheel-fr001'].geometry} material={materials['colormap.147']} position={[0.219, 0.188, -0.25]} />
      <mesh geometry={nodes['wheel-large'].geometry} material={materials['colormap.154']} />
      <mesh geometry={nodes['wheel-medium'].geometry} material={materials['colormap.155']} />
      <mesh geometry={nodes['wheel-small'].geometry} material={materials['colormap.156']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_1'].geometry} material={materials['colormap.085']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_2'].geometry} material={materials['colormap.089']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_3'].geometry} material={materials['colormap.086']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_4'].geometry} material={materials['colormap.090']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_5'].geometry} material={materials['colormap.091']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_6'].geometry} material={materials['colormap.092']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_7'].geometry} material={materials['colormap.093']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_8'].geometry} material={materials['colormap.094']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_9'].geometry} material={materials['colormap.095']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_10'].geometry} material={materials['colormap.096']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_11'].geometry} material={materials['colormap.097']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_12'].geometry} material={materials['colormap.098']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_13'].geometry} material={materials['colormap.099']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_14'].geometry} material={materials['colormap.100']} />
      <mesh geometry={nodes['track-striped-narrow-corner-small_15'].geometry} material={materials['colormap.101']} />
    </group>
  )
}

useGLTF.preload('/toy-car-racing.glb')
