/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\village_environment.glb -t 
Author: BigPo (https://sketchfab.com/BigPo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-environment-2e18c1baa9164093ad2e99e0a904363a
Title: Low poly environment
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Soil_Soil_texture_0: THREE.Mesh;
    Water_Water_texture_0: THREE.Mesh;
    Rock_Rock_texture_0: THREE.Mesh;
    Tree_2_Tree_2_texture_0: THREE.Mesh;
    Tree_1_Tree_1_texture_0: THREE.Mesh;
    Wood_Wood_texture_0: THREE.Mesh;
    Coppice_Coppice_texture_0: THREE.Mesh;
    Grass_Grass_texture_0: THREE.Mesh;
    Root_Root_texture_0: THREE.Mesh;
    Lotus_leaf_Lotus_leaf_texture_0: THREE.Mesh;
    Lantern_pole_Lantern_pole_texture_0: THREE.Mesh;
    Kerbstone_Kerbstone_texture_0: THREE.Mesh;
    Wooden_poles_Wooden_pole_texture_0: THREE.Mesh;
    Box_Box_texture_0: THREE.Mesh;
    Wood_floor_1_Wood_floor_1_texture_0: THREE.Mesh;
    Wood_floor_2_Wood_floor_2_texture_0: THREE.Mesh;
    Wood_floor_3_Wood_floor_3_texture_0: THREE.Mesh;
    Wood_floor_4_Wood_floor_4_texture_0: THREE.Mesh;
    Other_Other_texture_0: THREE.Mesh;
    Boat_Boat_texture_0: THREE.Mesh;
    Rickshaw_Rickshaw_texture_0: THREE.Mesh;
    Wooden_railings_1_Wooden_railings_1_texture_0: THREE.Mesh;
    Window_1_Window_1_texture_0: THREE.Mesh;
    B_House_1_B_house_1_texture_0: THREE.Mesh;
    Window_2_Window_2_texture_0: THREE.Mesh;
    B_House_2_B_house_2_texture_0: THREE.Mesh;
    Wooden_railings_3_Wooden_railings_3_texture_0: THREE.Mesh;
    Window_3_Window_3_texture_0: THREE.Mesh;
    Other_3_Other_3_texture_0: THREE.Mesh;
    B_House_3_B_house_3_texture_0: THREE.Mesh;
    Wooden_railings_4_Wooden_railings_4_texture_0: THREE.Mesh;
    Other_4_Other_4_texture_0: THREE.Mesh;
    Window_4_Window_4_texture_0: THREE.Mesh;
    B_House_4_B_House_4_texture_0: THREE.Mesh;
    Window_5_Window_5_texture_0: THREE.Mesh;
    Other_5_Other_5_texture_0: THREE.Mesh;
    Rotating_bowl_Rotating_bowl_texture_0: THREE.Mesh;
    B_House_5_B_House_5_texture_0: THREE.Mesh;
  };
  materials: {
    Soil_texture: THREE.MeshStandardMaterial;
    Water_texture: THREE.MeshStandardMaterial;
    Rock_texture: THREE.MeshStandardMaterial;
    Tree_2_texture: THREE.MeshStandardMaterial;
    Tree_1_texture: THREE.MeshStandardMaterial;
    Wood_texture: THREE.MeshStandardMaterial;
    Coppice_texture: THREE.MeshStandardMaterial;
    Grass_texture: THREE.MeshStandardMaterial;
    Root_texture: THREE.MeshStandardMaterial;
    Lotus_leaf_texture: THREE.MeshStandardMaterial;
    Lantern_pole_texture: THREE.MeshStandardMaterial;
    Kerbstone_texture: THREE.MeshStandardMaterial;
    Wooden_pole_texture: THREE.MeshStandardMaterial;
    Box_texture: THREE.MeshStandardMaterial;
    Wood_floor_1_texture: THREE.MeshStandardMaterial;
    Wood_floor_2_texture: THREE.MeshStandardMaterial;
    Wood_floor_3_texture: THREE.MeshStandardMaterial;
    Wood_floor_4_texture: THREE.MeshStandardMaterial;
    Other_texture: THREE.MeshStandardMaterial;
    Boat_texture: THREE.MeshStandardMaterial;
    Rickshaw_texture: THREE.MeshStandardMaterial;
    Wooden_railings_1_texture: THREE.MeshStandardMaterial;
    Window_1_texture: THREE.MeshStandardMaterial;
    B_house_1_texture: THREE.MeshStandardMaterial;
    Window_2_texture: THREE.MeshStandardMaterial;
    B_house_2_texture: THREE.MeshStandardMaterial;
    Wooden_railings_3_texture: THREE.MeshStandardMaterial;
    Window_3_texture: THREE.MeshStandardMaterial;
    Other_3_texture: THREE.MeshStandardMaterial;
    B_house_3_texture: THREE.MeshStandardMaterial;
    Wooden_railings_4_texture: THREE.MeshStandardMaterial;
    Other_4_texture: THREE.MeshStandardMaterial;
    Window_4_texture: THREE.MeshStandardMaterial;
    B_House_4_texture: THREE.MeshStandardMaterial;
    Window_5_texture: THREE.MeshStandardMaterial;
    Other_5_texture: THREE.MeshStandardMaterial;
    Rotating_bowl_texture: THREE.MeshStandardMaterial;
    B_House_5_texture: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function VillageEnvironment(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/village_environment.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={8.759}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Soil_Soil_texture_0.geometry}
            material={materials.Soil_texture}
          />
          <mesh
            geometry={nodes.Water_Water_texture_0.geometry}
            material={materials.Water_texture}
            position={[6.148, 4.421, -27]}
          />
          <mesh
            geometry={nodes.Rock_Rock_texture_0.geometry}
            material={materials.Rock_texture}
            position={[-14.075, 11.953, -25.513]}
          />
          <mesh
            geometry={nodes.Tree_2_Tree_2_texture_0.geometry}
            material={materials.Tree_2_texture}
          />
          <mesh
            geometry={nodes.Tree_1_Tree_1_texture_0.geometry}
            material={materials.Tree_1_texture}
          />
          <mesh
            geometry={nodes.Wood_Wood_texture_0.geometry}
            material={materials.Wood_texture}
          />
          <mesh
            geometry={nodes.Coppice_Coppice_texture_0.geometry}
            material={materials.Coppice_texture}
          />
          <mesh
            geometry={nodes.Grass_Grass_texture_0.geometry}
            material={materials.Grass_texture}
          />
          <mesh
            geometry={nodes.Root_Root_texture_0.geometry}
            material={materials.Root_texture}
          />
          <mesh
            geometry={nodes.Lotus_leaf_Lotus_leaf_texture_0.geometry}
            material={materials.Lotus_leaf_texture}
          />
          <mesh
            geometry={nodes.Lantern_pole_Lantern_pole_texture_0.geometry}
            material={materials.Lantern_pole_texture}
          />
          <mesh
            geometry={nodes.Kerbstone_Kerbstone_texture_0.geometry}
            material={materials.Kerbstone_texture}
          />
          <mesh
            geometry={nodes.Wooden_poles_Wooden_pole_texture_0.geometry}
            material={materials.Wooden_pole_texture}
          />
          <mesh
            geometry={nodes.Box_Box_texture_0.geometry}
            material={materials.Box_texture}
          />
          <mesh
            geometry={nodes.Wood_floor_1_Wood_floor_1_texture_0.geometry}
            material={materials.Wood_floor_1_texture}
          />
          <mesh
            geometry={nodes.Wood_floor_2_Wood_floor_2_texture_0.geometry}
            material={materials.Wood_floor_2_texture}
          />
          <mesh
            geometry={nodes.Wood_floor_3_Wood_floor_3_texture_0.geometry}
            material={materials.Wood_floor_3_texture}
          />
          <mesh
            geometry={nodes.Wood_floor_4_Wood_floor_4_texture_0.geometry}
            material={materials.Wood_floor_4_texture}
          />
          <mesh
            geometry={nodes.Other_Other_texture_0.geometry}
            material={materials.Other_texture}
          />
          <mesh
            geometry={nodes.Boat_Boat_texture_0.geometry}
            material={materials.Boat_texture}
          />
          <mesh
            geometry={nodes.Rickshaw_Rickshaw_texture_0.geometry}
            material={materials.Rickshaw_texture}
          />
          <mesh
            geometry={
              nodes.Wooden_railings_1_Wooden_railings_1_texture_0.geometry
            }
            material={materials.Wooden_railings_1_texture}
          />
          <mesh
            geometry={nodes.Window_1_Window_1_texture_0.geometry}
            material={materials.Window_1_texture}
          />
          <mesh
            geometry={nodes.B_House_1_B_house_1_texture_0.geometry}
            material={materials.B_house_1_texture}
            position={[-3.106, 14.267, -6.566]}
          />
          <mesh
            geometry={nodes.Window_2_Window_2_texture_0.geometry}
            material={materials.Window_2_texture}
          />
          <mesh
            geometry={nodes.B_House_2_B_house_2_texture_0.geometry}
            material={materials.B_house_2_texture}
          />
          <mesh
            geometry={
              nodes.Wooden_railings_3_Wooden_railings_3_texture_0.geometry
            }
            material={materials.Wooden_railings_3_texture}
          />
          <mesh
            geometry={nodes.Window_3_Window_3_texture_0.geometry}
            material={materials.Window_3_texture}
          />
          <mesh
            geometry={nodes.Other_3_Other_3_texture_0.geometry}
            material={materials.Other_3_texture}
          />
          <mesh
            geometry={nodes.B_House_3_B_house_3_texture_0.geometry}
            material={materials.B_house_3_texture}
          />
          <mesh
            geometry={
              nodes.Wooden_railings_4_Wooden_railings_4_texture_0.geometry
            }
            material={materials.Wooden_railings_4_texture}
          />
          <mesh
            geometry={nodes.Other_4_Other_4_texture_0.geometry}
            material={materials.Other_4_texture}
          />
          <mesh
            geometry={nodes.Window_4_Window_4_texture_0.geometry}
            material={materials.Window_4_texture}
          />
          <mesh
            geometry={nodes.B_House_4_B_House_4_texture_0.geometry}
            material={materials.B_House_4_texture}
          />
          <mesh
            geometry={nodes.Window_5_Window_5_texture_0.geometry}
            material={materials.Window_5_texture}
          />
          <mesh
            geometry={nodes.Other_5_Other_5_texture_0.geometry}
            material={materials.Other_5_texture}
          />
          <mesh
            geometry={nodes.Rotating_bowl_Rotating_bowl_texture_0.geometry}
            material={materials.Rotating_bowl_texture}
          />
          <mesh
            geometry={nodes.B_House_5_B_House_5_texture_0.geometry}
            material={materials.B_House_5_texture}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/village_environment.glb");
